README.md
Added a descriptive summary of the privacy properties of the API
=> Update Privacy Considerations summary

README.md
This change modifies the Permission delegation section to reflect the proposed changes on #14 .
=> Modify permission delegation

README.md
Implements the change described on #25
=> Change addestination attribute name

.pr-preview.json
From https://github.com/tobie/pr-preview#configuration-file
=> Turn on PR-Preview

index.bs
This PR creates the overall spec structures / sections and fills in a few structures and algorithms.
=> Scaffolding spec with high level sections and algorithms

README.md
=> Replaced "metadata" with "data"

README.md
As discussed with @johnidel and @csharrison.
=> Tweaks and fixes

README.md
These controls are accessible to anyone in the publisher's trusted top level context
=> Clarify that feature policy changes are "publisher-side"

noise_corrector.py
Fixes a few small problems with the file-level comments as well
=> Update and rename denoiser.py to noise_corrector.py

private_histograms_mpc.md
This PR adds a draft for an MPC protocol that supports some basic aggregation computation with differential privacy.
=> Add private_histograms_mpc.md

README.md
Fix small typo for "advertisers".
=> Fix typo advertisers

event_attribution_reporting.md
Adds a new readme which fleshes out the ideas discussed on #98
=> Add event_attribution_reporting.md to support views

AGGREGATE.md
Adds more details about 
- Integrating the worklet design
- Forming aggregation keys
- Privacy budgeting
- High level details about MPC protocol and example query model
=> Update AGGREGATE.md with more details

event_attribution_reporting.md
=> Return a promise from registerAttributionSource method

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/141.html" title="Last updated on May 7, 2021, 4:25 PM UTC (fc6c89e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/141/5c456e6...fc6c89e.html" title="Last updated on May 7, 2021, 4:25 PM UTC (fc6c89e)">Diff</a>
=> Spec storage for attribution sources and reports

index.bs
This is a copy of #141 which was reverted on #151
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/152.html" title="Last updated on May 28, 2021, 12:00 AM UTC (00d9689)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/152/5c456e6...00d9689.html" title="Last updated on May 28, 2021, 12:00 AM UTC (00d9689)">Diff</a>
=> Spec attribution caches

README.md
Adds the mechanism described on #153
=> Add priority to attribution trigger redirect

AGGREGATE.md, README.md, app_to_web.md, cross_device.md, event_attribution_reporting_clicks.md, event_attribution_reporting_views.md
=> New README

README.md, event_attribution_reporting_clicks.md
=> Add mechanism to deduplicate multiple triggers

event_attribution_reporting_clicks.md
Per https://wicg.github.io/conversion-measurement-api/#monkeypatch-anchor.
=> Specify attributionexpiry as signed in clicks explainer

index.bs
Also handle no matching sources and replace a nonexistent name from the attribution trigger algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/192.html" title="Last updated on Jul 23, 2021, 5:42 PM UTC (0019d0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/192/0b7446a...apasel422:0019d0c.html" title="Last updated on Jul 23, 2021, 5:42 PM UTC (0019d0c)">Diff</a>
=> Spec trigger deduplication

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/193.html" title="Last updated on Aug 6, 2021, 8:00 PM UTC (29f0eb9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/193/1f4084a...apasel422:29f0eb9.html" title="Last updated on Aug 6, 2021, 8:00 PM UTC (29f0eb9)">Diff</a>
=> Spec trigger priority

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/215.html" title="Last updated on Sep 9, 2021, 3:11 PM UTC (efc354d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/215/41221f9...apasel422:efc354d.html" title="Last updated on Sep 9, 2021, 3:11 PM UTC (efc354d)">Diff</a>
=> Fix typos and formatting in draft spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/235.html" title="Last updated on Sep 27, 2021, 3:36 PM UTC (6dfa75d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/235/94c91d9...6dfa75d.html" title="Last updated on Sep 27, 2021, 3:36 PM UTC (6dfa75d)">Diff</a>
=> Add John Delaney as spec editor

index.bs
Fixes #240
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 5, 2021, 6:43 PM UTC)_.
<details>
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2FWICG%2Fconversion-measurement-api%2Fpull%2F241%2F79e0cf5.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fapasel422%2Fconversion-measurement-api%2Fpull%2F241.html)
```
<html><body><h1>503 Service Unavailable</h1>
No server is available to …
```
=> Require source/trigger origins to be non-opaque

index.bs
Fixes #246
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/253.html" title="Last updated on Nov 9, 2021, 5:54 PM UTC (b20f603)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/253/ee4f982...apasel422:b20f603.html" title="Last updated on Nov 9, 2021, 5:54 PM UTC (b20f603)">Diff</a>
=> Spec attribution rate-limiting

AGGREGATE.md
=> Remove format version field from keys.json

AGGREGATE.md
=> Disallow repeated key IDs

AGGREGATE.md
This is more succinct and allows for more flexibility in the data processing design
=> Rename operation to "histogram"

README.md
Replaced obsolete resources with link to all resources
=> Replaced obsolete resources with link to all resources

README.md, event_attribution_reporting_clicks.md
Fixes #264 
(Not fully since we don't have newcomer-friendly blogposts for all explainers yet)
=> Added links to blogposts

index.bs
Per the latest explainer updates.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/291.html" title="Last updated on Jan 27, 2022, 4:51 PM UTC (38d2cc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/291/ad34b89...apasel422:38d2cc0.html" title="Last updated on Jan 27, 2022, 4:51 PM UTC (38d2cc0)">Diff</a>
=> Remove trigger data noising

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/284.html" title="Last updated on Jan 28, 2022, 7:59 PM UTC (1e8bfe8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/284/cdb6689...apasel422:1e8bfe8.html" title="Last updated on Jan 28, 2022, 7:59 PM UTC (1e8bfe8)">Diff</a>
=> Prefix trigger data with navigation-source to avoid confusion

EVENT.md
The document covers clicks and views now
=> Update event-level API intro

AGGREGATE.md, EVENT.md
This will allow the aggregation service to dedupe duplicate reports.
=> [aggregate] move report_id to shared_info

AGGREGATE.md
=> scheduled_report_time should be a string

EVENT.md
For consistency with debug keys.
Fixes #316.
=> Make trigger deduplication keys unsigned

AGGREGATE.md
This aligns with other fields like source_site
=> Move source_registration_time into privacy_budget_key

AGGREGATE.md
=> Add duplicate debug aggregatable reports

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/397.html" title="Last updated on May 3, 2022, 2:01 PM UTC (ba88c85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/397/54a3a50...apasel422:ba88c85.html" title="Last updated on May 3, 2022, 2:01 PM UTC (ba88c85)">Diff</a>
=> Introduce type for source types

EVENT.md
=> Encode attributionsrc URLs passed to window.open in event explainer

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/418.html" title="Last updated on May 10, 2022, 1:37 PM UTC (0ead95b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/418/ae0fc40...apasel422:0ead95b.html" title="Last updated on May 10, 2022, 1:37 PM UTC (0ead95b)">Diff</a>
=> Add missing references to spec

index.bs
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/414.html" title="Last updated on May 9, 2022, 4:09 PM UTC (b1d502f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/414/c7a5506...apasel422:b1d502f.html" title="Last updated on May 9, 2022, 4:09 PM UTC (b1d502f)">Diff</a>
=> Specify source expiry clamping

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#storage-limits
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/412.html" title="Last updated on May 10, 2022, 7:08 PM UTC (6424877)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/412/f857acd...apasel422:6424877.html" title="Last updated on May 10, 2022, 7:08 PM UTC (6424877)">Diff</a>
=> Specify limits on pending sources per source origin

index.bs
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/419.html" title="Last updated on May 11, 2022, 12:28 PM UTC (3e0dc69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/419/f56b39e...apasel422:3e0dc69.html" title="Last updated on May 11, 2022, 12:28 PM UTC (3e0dc69)">Diff</a>
=> Specify randomized responses for navigation sources

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/425.html" title="Last updated on May 11, 2022, 7:11 PM UTC (d0e99a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/425/c5699b2...d0e99a6.html" title="Last updated on May 11, 2022, 7:11 PM UTC (d0e99a6)">Diff</a>
=> Early return for sources with non-empty randomized response

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#triggering-attribution
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#optional-attribution-filters
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/402.html" title="Last updated on May 11, 2022, 12:47 PM UTC (28a0fa3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/402/3335cf0...apasel422:28a0fa3.html" title="Last updated on May 11, 2022, 12:47 PM UTC (28a0fa3)">Diff</a>
=> Specify event-level trigger configurations

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/449.html" title="Last updated on May 24, 2022, 3:35 PM UTC (500310e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/449/0768be8...apasel422:500310e.html" title="Last updated on May 24, 2022, 3:35 PM UTC (500310e)">Diff</a>
=> Add references to request fields

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/450.html" title="Last updated on May 24, 2022, 4:26 PM UTC (da165cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/450/322f54f...apasel422:da165cb.html" title="Last updated on May 24, 2022, 4:26 PM UTC (da165cb)">Diff</a>
=> Remove trailing whitespace

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/453.html" title="Last updated on May 25, 2022, 1:34 PM UTC (e9512bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/453/2f64cba...apasel422:e9512bd.html" title="Last updated on May 25, 2022, 1:34 PM UTC (e9512bd)">Diff</a>
=> Capitalize ID when used in prose

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/454.html" title="Last updated on May 25, 2022, 2:35 PM UTC (948720b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/454/d369867...apasel422:948720b.html" title="Last updated on May 25, 2022, 2:35 PM UTC (948720b)">Diff</a>
=> Group vendor-specific parameters in a single section

AGGREGATE.md, AGGREGATION_SERVICE_TEE.md
Begins to addresses issue #439
=> Remove the source site from aggregatable reports and privacy budget key

AGGREGATE.md
=> Replace aggregatable-specific source headers with optional fields on Register-Source header

EVENT.md
=> Replace boolean Attribution-Reporting-Eligible header with dictionary

AGGREGATE.md
=> Replace aggregatable source registration JSON list with dict

AGGREGATE.md, EVENT.md
=> Consolidate attributon trigger headers

index.bs
Corresponding to #434
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/459.html" title="Last updated on May 26, 2022, 9:59 PM UTC (4fbe197)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/459/6610747...apasel422:4fbe197.html" title="Last updated on May 26, 2022, 9:59 PM UTC (4fbe197)">Diff</a>
=> Add issue for parsing source aggregation keys

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/455.html" title="Last updated on May 26, 2022, 6:29 PM UTC (dbd5ce3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/455/77eb189...apasel422:dbd5ce3.html" title="Last updated on May 26, 2022, 6:29 PM UTC (dbd5ce3)">Diff</a>
=> Merge aggregatable trigger struct into general trigger struct

EVENT.md
Resolves https://github.com/WICG/conversion-measurement-api/issues/378
=> Make the attributionsrc ping optional

index.bs
Corresponds to #448.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/458.html" title="Last updated on May 27, 2022, 12:43 PM UTC (54e5a75)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/458/6610747...apasel422:54e5a75.html" title="Last updated on May 27, 2022, 12:43 PM UTC (54e5a75)">Diff</a>
=> Specify optional event-trigger registration

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/467.html" title="Last updated on Jun 1, 2022, 1:35 PM UTC (6f2bb9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/467/13a9961...apasel422:6f2bb9e.html" title="Last updated on Jun 1, 2022, 1:35 PM UTC (6f2bb9e)">Diff</a>
=> Link assertions in spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/468.html" title="Last updated on Jun 6, 2022, 7:05 PM UTC (85495ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/468/40bfa3a...apasel422:85495ac.html" title="Last updated on Jun 6, 2022, 7:05 PM UTC (85495ac)">Diff</a>
=> Specify filter-data parsing

EVENT.md, index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/477.html" title="Last updated on Jun 16, 2022, 1:57 PM UTC (1caed10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/477/0a1cbfc...apasel422:1caed10.html" title="Last updated on Jun 16, 2022, 1:57 PM UTC (1caed10)">Diff</a>
=> Add top-level negated filters

header-validator/logger.js
=> Added logger

header-validator/index.js, header-validator/validate-json.js
=> Handle non-object values gracefully

header-validator/README.md, header-validator/data.source.js, header-validator/data.trigger.js, header-validator/logger.js, header-validator/package.json, header-validator/test.source.js, header-validator/test.trigger.js
Partly fixes #503 
@apasel422 
To run:
`npm run test`
`npm run test-trigger`
=> Added npm scripts and trigger test headers

AGGREGATION_SERVICE_TEE.md
This fix has been reviewed by an agg report point of contact.
=> Fixed shared ID description

index.bs
Fixes #277
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/555.html" title="Last updated on Sep 14, 2022, 12:10 PM UTC (f53cb67)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/555/ef4e66c...apasel422:f53cb67.html" title="Last updated on Sep 14, 2022, 12:10 PM UTC (f53cb67)">Diff</a>
=> Gate navigation sources by transient activation

AGGREGATE.md
=> Allow source expiry to be independently configured for aggregatable attribution

ara-tester-list.md
This is PR listing us in the PoC companies. Please confirm this.
=> Adding SMN in the tester list

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/473.html" title="Last updated on Oct 3, 2022, 1:33 PM UTC (0171911)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/473/7deae4b...0171911.html" title="Last updated on Oct 3, 2022, 1:33 PM UTC (0171911)">Diff</a>
=> Specify aggregatable source and trigger parsing

ara-tester-list.md
This is Yahoo! JAPAN.
I am sending a pull request to be listed as a PoC participating company. Please confirm.
=> Update ara-tester-list.md from Yahoo! JAPAN

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/568.html" title="Last updated on Oct 3, 2022, 3:33 PM UTC (c650dfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/568/67387ca...c650dfc.html" title="Last updated on Oct 3, 2022, 3:33 PM UTC (c650dfc)">Diff</a>
=> Specify parsing aggregatable_expiry and aggregatable_deduplication_key

EVENT.md
=> Change unique destination limit for sources to be time bounded

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/575.html" title="Last updated on Oct 14, 2022, 5:18 PM UTC (8729796)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/575/ba90ce3...8729796.html" title="Last updated on Oct 14, 2022, 5:18 PM UTC (8729796)">Diff</a>
=> Update spec for unique destination limit

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/478.html" title="Last updated on Oct 17, 2022, 8:47 PM UTC (1d0258e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/478/737c5cd...1d0258e.html" title="Last updated on Oct 17, 2022, 8:47 PM UTC (1d0258e)">Diff</a>
=> Specify aggregatable report delivery

AGGREGATE.md, EVENT.md, header-validator/data.source.js, header-validator/validate-json.js, index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/577.html" title="Last updated on Oct 25, 2022, 4:51 PM UTC (1e430ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/577/be60ef1...1e430ff.html" title="Last updated on Oct 25, 2022, 4:51 PM UTC (1e430ff)">Diff</a>
=> Replace aggregatable_expiry with event_attribution_window

index.bs
https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#optional-verbose-debugging-reports
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/597.html" title="Last updated on Oct 28, 2022, 9:30 PM UTC (183a598)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/597/f375e96...183a598.html" title="Last updated on Oct 28, 2022, 9:30 PM UTC (183a598)">Diff</a>
=> Specify error debug reports

header-validator/data.trigger.js, header-validator/validate-json.js
This should have been part of #589.
=> Validate trigger debug_reporting field

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/600.html" title="Last updated on Nov 9, 2022, 6:30 PM UTC (b0accd7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/600/015013b...apasel422:b0accd7.html" title="Last updated on Nov 9, 2022, 6:30 PM UTC (b0accd7)">Diff</a>
=> Remove broken/obsolete navigation monkeypatches

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/613.html" title="Last updated on Nov 21, 2022, 6:18 PM UTC (d7cd970)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/613/14b657c...d7cd970.html" title="Last updated on Nov 21, 2022, 6:18 PM UTC (d7cd970)">Diff</a>
=> Spec verbose debug reports for source registration

index.bs
Also spec debug reporting in the case of no matching source.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/623.html" title="Last updated on Nov 21, 2022, 6:35 PM UTC (141c338)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/623/f01a3f6...141c338.html" title="Last updated on Nov 21, 2022, 6:35 PM UTC (141c338)">Diff</a>
=> Spec trigger debug reporting header parsing

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/625.html" title="Last updated on Nov 22, 2022, 3:44 PM UTC (56a93f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/625/6ba9132...apasel422:56a93f5.html" title="Last updated on Nov 22, 2022, 3:44 PM UTC (56a93f5)">Diff</a>
=> Clone aggregation-key set to avoid updating it in place

index.bs
This is to to prepare spec verbose debug reports for trigger registrations, and ensure that proper error is reported.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/624.html" title="Last updated on Nov 22, 2022, 3:45 PM UTC (c18ae2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/624/d91d2fa...c18ae2f.html" title="Last updated on Nov 22, 2022, 3:45 PM UTC (c18ae2f)">Diff</a>
=> Reorder checks in event-level and aggregatable trigger algorithms

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/630.html" title="Last updated on Nov 23, 2022, 1:46 PM UTC (23aabe1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/630/73acb0e...apasel422:23aabe1.html" title="Last updated on Nov 23, 2022, 1:46 PM UTC (23aabe1)">Diff</a>
=> Define enum types to allow cross-referencing

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/632.html" title="Last updated on Nov 23, 2022, 7:08 PM UTC (1c73ac9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/632/3e5d1db...1c73ac9.html" title="Last updated on Nov 23, 2022, 7:08 PM UTC (1c73ac9)">Diff</a>
=> Spec debug reports for event-level trigger errors

header-validator/data.trigger.js, header-validator/validate-json.js, index.bs
Fixes #617.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/633.html" title="Last updated on Nov 23, 2022, 8:06 PM UTC (1691ab7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/633/bfc0e7d...linnan-github:1691ab7.html" title="Last updated on Nov 23, 2022, 8:06 PM UTC (1691ab7)">Diff</a>
=> Update spec to make source keys in aggregatable trigger data optional

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/627.html" title="Last updated on Nov 22, 2022, 4:05 PM UTC (2268e0f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/627/9e9256a...apasel422:2268e0f.html" title="Last updated on Nov 22, 2022, 4:05 PM UTC (2268e0f)">Diff</a>
=> Require suitable origins to have an http/https scheme

.github/workflows/test-header-validator.yml
=> Test header validator on relevant commits

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/481.html" title="Last updated on Nov 30, 2022, 8:38 PM UTC (22cdbcb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/481/9da4aba...22cdbcb.html" title="Last updated on Nov 30, 2022, 8:38 PM UTC (22cdbcb)">Diff</a>
=> Specify shared info and aggregation service payloads for aggregatable report

app_to_web.md
=> Update the explainer for Accept-Attribution-Reporting-Support

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/669.html" title="Last updated on Jan 12, 2023, 7:10 PM UTC (b73f817)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/669/fb9fbbe...apasel422:b73f817.html" title="Last updated on Jan 12, 2023, 7:10 PM UTC (b73f817)">Diff</a>
=> Use moment and duration spec concepts

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/671.html" title="Last updated on Jan 19, 2023, 2:57 PM UTC (4b7ae0e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/671/5e102d4...linnan-github:4b7ae0e.html" title="Last updated on Jan 19, 2023, 2:57 PM UTC (4b7ae0e)">Diff</a>
=> Spec change for updating attribution rate limit for noised source

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/675.html" title="Last updated on Jan 19, 2023, 6:07 PM UTC (0d9354a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/675/c2394f3...apasel422:0d9354a.html" title="Last updated on Jan 19, 2023, 6:07 PM UTC (0d9354a)">Diff</a>
=> Specify debug cookie checks

README.md
Primary change: Update the implementation status of the app-to-web explainer.
Additionally, some smaller style and grammar tweaks for clarity and accessibility.
=> App-to-web update

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/690.html" title="Last updated on Jan 24, 2023, 3:57 PM UTC (9d2b778)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/690/be461e4...apasel422:9d2b778.html" title="Last updated on Jan 24, 2023, 3:57 PM UTC (9d2b778)">Diff</a>
=> Fix miscellaneous formatting issues

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/691.html" title="Last updated on Jan 24, 2023, 4:14 PM UTC (3b7099a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/691/8254980...apasel422:3b7099a.html" title="Last updated on Jan 24, 2023, 4:14 PM UTC (3b7099a)">Diff</a>
=> Move algorithms to appropriate sections and remove unnecessary headings

EVENT.md, header-validator/data.source.js, header-validator/data.trigger.js, header-validator/utils.js, header-validator/validate-json.js, index.bs
Fixes #615
***
<a href="https://pr-preview.s3.amazonaws.com/agarant/attribution-reporting-api/pull/634.html" title="Last updated on Feb 9, 2023, 9:10 PM UTC (4e6c26a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/634/87d93cc...agarant:4e6c26a.html" title="Last updated on Feb 9, 2023, 9:10 PM UTC (4e6c26a)">Diff</a>
=> Support multiple sets of OR'd filters

EVENT.md
Suggested EVENT explainer tweak for multiple destinations.
=> Clarifications in wake of multiple destinations support landing

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/719.html" title="Last updated on Mar 8, 2023, 2:15 PM UTC (68f6c90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/719/501f427...apasel422:68f6c90.html" title="Last updated on Mar 8, 2023, 2:15 PM UTC (68f6c90)">Diff</a>
=> Specify Clear Site Data integration

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/726.html" title="Last updated on Mar 17, 2023, 2:35 PM UTC (79fe117)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/726/f371279...apasel422:79fe117.html" title="Last updated on Mar 17, 2023, 2:35 PM UTC (79fe117)">Diff</a>
=> Add basic cross app and web section to spec

flexible_event_config.md
This document proposes an extension to event-level reports that increases their flexibility.
=> Add flexible_event_config.md

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/723.html" title="Last updated on Mar 29, 2023, 3:28 PM UTC (c89bc83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/723/4e0d46a...apasel422:c89bc83.html" title="Last updated on Mar 29, 2023, 3:28 PM UTC (c89bc83)">Diff</a>
=> Specify background attributionsrc requests

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/743.html" title="Last updated on Mar 29, 2023, 9:50 PM UTC (ab08a1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/743/fe171ff...apasel422:ab08a1d.html" title="Last updated on Mar 29, 2023, 9:50 PM UTC (ab08a1d)">Diff</a>
=> Add missing link to eligibility

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/751.html" title="Last updated on Apr 5, 2023, 1:01 PM UTC (b8af819)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/751/bb7dce6...linnan-github:b8af819.html" title="Last updated on Apr 5, 2023, 1:01 PM UTC (b8af819)">Diff</a>
=> minor fix for aggregation coordinator spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/762.html" title="Last updated on Apr 14, 2023, 5:05 PM UTC (d996b3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/762/e7d6d7d...apasel422:d996b3c.html" title="Last updated on Apr 14, 2023, 5:05 PM UTC (d996b3c)">Diff</a>
=> Check permission policy and document's secure context

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/745.html" title="Last updated on Apr 4, 2023, 12:40 PM UTC (164ae86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/745/ec2982b...apasel422:164ae86.html" title="Last updated on Apr 4, 2023, 12:40 PM UTC (164ae86)">Diff</a>
=> Specify OS-registration header processing

index.bs
Fixed in #745
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/764.html" title="Last updated on Apr 17, 2023, 1:03 PM UTC (6448eb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/764/b7263ac...apasel422:6448eb1.html" title="Last updated on Apr 17, 2023, 1:03 PM UTC (6448eb1)">Diff</a>
=> Remove obsolete OS-registration issue

AGGREGATE.md, report_verification.md
=> Update explainer for reducing delays for aggregatable reports

EVENT.md, index.bs
#756
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/757.html" title="Last updated on Apr 19, 2023, 4:48 PM UTC (dfaf258)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/757/a82aaf0...apasel422:dfaf258.html" title="Last updated on Apr 19, 2023, 4:48 PM UTC (dfaf258)">Diff</a>
=> Replace manual fetch/XHR headers with first-class option

app_to_web.md
This was accidentally merged by mistake.
=> Revert explainer change for web support

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/773.html" title="Last updated on May 3, 2023, 2:35 PM UTC (7624ba5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/773/1a814ef...apasel422:7624ba5.html" title="Last updated on May 3, 2023, 2:35 PM UTC (7624ba5)">Diff</a>
=> Monkeypatch fetch using Attribution Reporting eligibility

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/776.html" title="Last updated on May 3, 2023, 3:33 PM UTC (5ed4072)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/776/46b9428...apasel422:5ed4072.html" title="Last updated on May 3, 2023, 3:33 PM UTC (5ed4072)">Diff</a>
=> Monkeypatch XHR using Attribution Reporting eligibility

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/782.html" title="Last updated on May 4, 2023, 6:03 PM UTC (c2cf742)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/782/ad3fcc2...linnan-github:c2cf742.html" title="Last updated on May 4, 2023, 6:03 PM UTC (c2cf742)">Diff</a>
=> Not sending background attributionsrc request if no registrar is supported

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/783.html" title="Last updated on May 4, 2023, 6:27 PM UTC (74866ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/783/a73a0b1...linnan-github:74866ac.html" title="Last updated on May 4, 2023, 6:27 PM UTC (74866ac)">Diff</a>
=> Clean up for aggregatableExpiry

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/777.html" title="Last updated on May 3, 2023, 6:36 PM UTC (b711866)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/777/c83fa51...apasel422:b711866.html" title="Last updated on May 3, 2023, 6:36 PM UTC (b711866)">Diff</a>
=> Begin specifying navigation integration

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/785.html" title="Last updated on May 9, 2023, 2:10 PM UTC (2163d7d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/785/9debabb...linnan-github:2163d7d.html" title="Last updated on May 9, 2023, 2:10 PM UTC (2163d7d)">Diff</a>
=> Reject JSON if aggregatable value is greater than max budget

AGGREGATE.md
=> Limit on the number of aggregatable reports per source

AGGREGATE.md
This is not relevant anymore with null reports.
=> Remove irrelevant statement about true number of aggregatable reports

index.bs
Fixes #807
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/811.html" title="Last updated on May 17, 2023, 2:01 PM UTC (b83acc1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/811/c57b6e3...apasel422:b83acc1.html" title="Last updated on May 17, 2023, 2:01 PM UTC (b83acc1)">Diff</a>
=> Make Navigation Monkeypatches a subsection of HTML ones

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/810.html" title="Last updated on May 17, 2023, 1:53 PM UTC (f3e5a0f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/810/c57b6e3...apasel422:f3e5a0f.html" title="Last updated on May 17, 2023, 1:53 PM UTC (f3e5a0f)">Diff</a>
=> Add note about user-initiated deletion controls

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/814.html" title="Last updated on May 17, 2023, 5:51 PM UTC (becc14b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/814/7ef1f9b...apasel422:becc14b.html" title="Last updated on May 17, 2023, 5:51 PM UTC (becc14b)">Diff</a>
=> Add section on reporting-delay privacy concerns

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/816.html" title="Last updated on May 18, 2023, 8:46 PM UTC (4b12a26)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/816/84aa0c2...4b12a26.html" title="Last updated on May 18, 2023, 8:46 PM UTC (4b12a26)">Diff</a>
=> Add a few more privacy consideration sections

index.bs
#725
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/791.html" title="Last updated on May 16, 2023, 9:03 PM UTC (d81cca3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/791/2aa8f51...d81cca3.html" title="Last updated on May 16, 2023, 9:03 PM UTC (d81cca3)">Diff</a>
=> Per-reporting-site reporting origin limits

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/821.html" title="Last updated on May 19, 2023, 12:26 AM UTC (0adb30e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/821/0e687a2...0adb30e.html" title="Last updated on May 19, 2023, 12:26 AM UTC (0adb30e)">Diff</a>
=> Add some links to the privacy considerations

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/828.html" title="Last updated on May 30, 2023, 4:27 PM UTC (855afee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/828/0e16b7f...apasel422:855afee.html" title="Last updated on May 30, 2023, 4:27 PM UTC (855afee)">Diff</a>
=> Remove issue for source-registration destination limit

EVENT.md
=> New fine-grained destination limit across reporting origins - explainer update

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/831.html" title="Last updated on May 31, 2023, 7:42 PM UTC (50a3f8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/831/e6b60e4...50a3f8f.html" title="Last updated on May 31, 2023, 7:42 PM UTC (50a3f8f)">Diff</a>
=> Add a few sections to the security considerations

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/837.html" title="Last updated on Jun 8, 2023, 3:31 PM UTC (30f114a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/837/59892b2...apasel422:30f114a.html" title="Last updated on Jun 8, 2023, 3:31 PM UTC (30f114a)">Diff</a>
=> Clarify bitwise-OR

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/844.html" title="Last updated on Jun 9, 2023, 4:18 PM UTC (a19e32c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/844/2994e7f...linnan-github:a19e32c.html" title="Last updated on Jun 9, 2023, 4:18 PM UTC (a19e32c)">Diff</a>
=> Add issues for fenced reporting reporting beacon integration

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/838.html" title="Last updated on Jun 8, 2023, 4:25 PM UTC (97e3854)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/838/59892b2...97e3854.html" title="Last updated on Jun 8, 2023, 4:25 PM UTC (97e3854)">Diff</a>
=> Update issue on redirect handling with fetch

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/853.html" title="Last updated on Jun 21, 2023, 2:35 PM UTC (4c4fec4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/853/2232e44...linnan-github:4c4fec4.html" title="Last updated on Jun 21, 2023, 2:35 PM UTC (4c4fec4)">Diff</a>
=> Spec greasing Attribution-Reporting-Support header

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/848.html" title="Last updated on Jun 22, 2023, 2:05 AM UTC (71732b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/848/aef3a7b...linnan-github:71732b5.html" title="Last updated on Jun 22, 2023, 2:05 AM UTC (71732b5)">Diff</a>
=> Monkeypatch fenced frame beacon sending

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/859.html" title="Last updated on Jun 26, 2023, 4:16 PM UTC (9517bd9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/859/8b0014b...linnan-github:9517bd9.html" title="Last updated on Jun 26, 2023, 4:16 PM UTC (9517bd9)">Diff</a>
=> Monkeypatch fenced frame beacon response

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/874.html" title="Last updated on Jun 28, 2023, 1:24 PM UTC (e4bc5cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/874/1779655...apasel422:e4bc5cb.html" title="Last updated on Jun 28, 2023, 1:24 PM UTC (e4bc5cb)">Diff</a>
=> Minor formatting changes for spec

app_to_web.md, header-validator/test.os.js, header-validator/validate-os.js, index.bs, validate-headers.html
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/873.html" title="Last updated on Jun 29, 2023, 6:13 PM UTC (eaa4548)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/873/fd49fc1...linnan-github:eaa4548.html" title="Last updated on Jun 29, 2023, 6:13 PM UTC (eaa4548)">Diff</a>
=> Update explainer and spec for OS registration delegated debug reports

ara-tester-list.md
Teads participates to ARA testing.
=> Add Teads to ara-tester-list.md

index.bs
Fixes #867
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/868.html" title="Last updated on Jul 5, 2023, 2:59 PM UTC (a958b0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/868/b5d8bdf...linnan-github:a958b0c.html" title="Last updated on Jul 5, 2023, 2:59 PM UTC (a958b0c)">Diff</a>
=> Export attribution-reporting permission policy

index.bs
Resolves #842. Renamed to reflect agreed upon changes.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/851.html" title="Last updated on Jun 27, 2023, 5:30 PM UTC (c77b36f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/851/d8e02e8...c77b36f.html" title="Last updated on Jun 27, 2023, 5:30 PM UTC (c77b36f)">Diff</a>
=> Move source deactivation step after top level filter matching

index.bs
Fixes a link and clarifies the prose slightly. See https://github.com/patcg-individual-drafts/private-aggregation-api/pull/64#discussion_r1257856353 for explanation.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/884.html" title="Last updated on Jul 10, 2023, 5:48 PM UTC (7435404)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/884/c42e8ee...7435404.html" title="Last updated on Jul 10, 2023, 5:48 PM UTC (7435404)">Diff</a>
=> Small improvement to WebDriver wording

flexible_event_config.md
Fixes some examples which incorrectly indicated a batching mechanism. Also beefs up some comments.
=> Minor fixes and clarifications to flex explainer

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/897.html" title="Last updated on Jul 18, 2023, 7:03 PM UTC (116977e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/897/412bdd6...apasel422:116977e.html" title="Last updated on Jul 18, 2023, 7:03 PM UTC (116977e)">Diff</a>
=> Clean up event-level report-prioritization algorithm

header-validator/data.source.js, header-validator/validate-json.js, schema/source.schema.json, schema/test.js
=> Allow integer duration fields in schema and header validator

flexible_event_config.md
=> Re-add start_time to flex event

header-validator/package-lock.json, header-validator/package.json
This picks up the fix for
https://github.com/badgateway/structured-headers/issues/47.
=> Update structured-headers dependency

.github/workflows/build.yml, .github/workflows/test-header-validator.yml
These workflows should match files in nested directories, not just the top one.
=> Fix globbing in workflows

flexible-event/privacy.ts
Will add some tests in a follow-up.
=> Fix incorrect impl flipProbabilityDp

index.bs
Solves #921, approved on #924
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/925.html" title="Last updated on Jul 31, 2023, 7:20 PM UTC (07bcef2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/925/bd0512d...07bcef2.html" title="Last updated on Jul 31, 2023, 7:20 PM UTC (07bcef2)">Diff</a>
=> Spec UA abort flows 

EVENT.md, header-validator/src/source.data.test.ts, header-validator/src/trigger.data.test.ts, header-validator/src/validate-json.ts
Update the explainer and header validator according to spec changes introduced in #914.
=> Lookback window: explainer & validator

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/944.html" title="Last updated on Aug 10, 2023, 6:34 PM UTC (ae09dc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/944/53c270c...ae09dc8.html" title="Last updated on Aug 10, 2023, 6:34 PM UTC (ae09dc8)">Diff</a>
=> Fix typo in parse report windows

header-validator/src/trigger.data.test.ts, header-validator/src/validate-json.ts
Should have been part of #942.
=> Warn about duplicate filter values

header-validator/src/validate-json.ts
This improves readability and avoids the need to default values in all locations.
=> Extract optional parameters into a type

flexible_event_config.md
Update to privacy considerations section
=> Update flexible_event_config.md - update privacy considerations

params/chromium-params.md
Adding navigation and event information gain bounds
=> Update chromium-params.md - information gain bounds

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/964.html" title="Last updated on Aug 21, 2023, 2:09 PM UTC (b5dbf62)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/964/900f657...apasel422:b5dbf62.html" title="Last updated on Aug 21, 2023, 2:09 PM UTC (b5dbf62)">Diff</a>
=> Extract helper algorithm for parsing filters

EVENT.md, header-validator/src/source.test.ts, header-validator/src/trigger.test.ts, header-validator/src/validate-json.ts, index.bs
Fix #930
***
<a href="https://pr-preview.s3.amazonaws.com/agarant/attribution-reporting-api/pull/967.html" title="Last updated on Aug 23, 2023, 1:43 PM UTC (235837e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/967/871c4be...agarant:235837e.html" title="Last updated on Aug 23, 2023, 1:43 PM UTC (235837e)">Diff</a>
=> Reserve keys starting with an underscore

header-validator/src/source.test.ts, header-validator/src/trigger.test.ts, header-validator/src/validate-json.ts
- Use [ instead of ( for bound of aggregatable value, since range is inclusive
- Consolidate common fields
- Remove redundant code
- Remove duplicated values
- Clarify HTTP/HTTPS for URLs
=> Miscellaneous header-validator cleanup/fixes

header-validator/src/context.ts, header-validator/src/source.test.ts, header-validator/src/validate-json.ts
This will make future enhancements like displaying the effective
source registration, given a source type, possible, and will allow for
cross-field validation.
=> Parse dictionaries into well-typed structures

header-validator/src/validate-json.ts
This uses the same structure as the spec.
=> Parse lookback window into well-typed FilterConfig struct

header-validator/src/maybe.ts, header-validator/src/validate-json.ts
This makes it possible to merge map and flatMap, which will simplify additional refactoring in #986.
=> Replace separate Some/None types with Maybe class

.github/workflows/lint-header-validator.yml, header-validator/package.json, header-validator/src/validate-json.ts
Check lint on CI, tested with the first commit which had linting error.
=> Check lint on CI

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/997.html" title="Last updated on Sep 7, 2023, 3:42 PM UTC (3968e1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/997/e9322b5...3968e1c.html" title="Last updated on Sep 7, 2023, 3:42 PM UTC (3968e1c)">Diff</a>
=> Fix unintended step numbering

header-validator/src/validate-json.ts
Now that the validator is source-type-aware, this will allow us to show the effective windows in the UI and use them for channel-capacity computations.
=> Resolve default event report windows in header validator

ara-tester-list.md
Hello WICG!
Yahoo Inc would like to be added to the list of API testers.  We are planning to try out the Attribution Reporting API for DSP use cases.
Thank you!
=> Add Yahoo Inc to ara-tester-list.md

AGGREGATE.md
See issue #352 and the corresponding spec change #1030.
=> Add padding the payload to the aggregate explainer

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
Instead of checking it for each value.
=> Check presence of expiry and start time before processing end times

index.bs
Will prepare a PR to move the monkeypatch to fenced frame spec soon.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1051.html" title="Last updated on Sep 30, 2023, 8:50 PM UTC (21b2b47)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1051/ce437a6...linnan-github:21b2b47.html" title="Last updated on Sep 30, 2023, 8:50 PM UTC (21b2b47)">Diff</a>
=> Fix build due to fenced frame spec update

EVENT.md, flexible_event_config.md
Since it is no longer a possible enhancement, but a specified and implemented one.
=> Move Flex Lite description to primary event-level explainer

index.bs
…me spec
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1056.html" title="Last updated on Oct 2, 2023, 7:08 PM UTC (21a704d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1056/cc570a4...linnan-github:21a704d.html" title="Last updated on Oct 2, 2023, 7:08 PM UTC (21a704d)">Diff</a>
=> More exports to allow moving fenced frame monkeypatches to fenced frame spec

index.bs
Will be used in fenced frame spec. Thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1058.html" title="Last updated on Oct 3, 2023, 4:03 PM UTC (26d4209)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1058/b8d2b90...linnan-github:26d4209.html" title="Last updated on Oct 3, 2023, 4:03 PM UTC (26d4209)">Diff</a>
=> Two more exports

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1085.html" title="Last updated on Oct 24, 2023, 2:46 PM UTC (86fef5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1085/bc9f1df...apasel422:86fef5b.html" title="Last updated on Oct 24, 2023, 2:46 PM UTC (86fef5b)">Diff</a>
=> Use range algorithms in spec

AGGREGATE.md
=> Explainer update for supporting trigger context ID and avoiding report delay for aggregate reporting

ts/src/header-validator/validate-json.ts
=> Remove obsolete TODOs from header validator

index.bs
This makes the spec consistent with [what Chromium is already doing](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/attribution_src_loader.cc;l=569-575;drc=d3d4ff28768842dd1ce94f408f89d1e2d31dd4fd).
Related to #767, though this has no effect on URLs being redirected through.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 2, 2024, 1:18 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related …
=> Require background attributionsrc URL to be suitable

index.bs
To aligns with the implementation.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1159.html" title="Last updated on Feb 7, 2024, 11:30 PM UTC (b1a45d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1159/2cac7f3...linnan-github:b1a45d1.html" title="Last updated on Feb 7, 2024, 11:30 PM UTC (b1a45d1)">Diff</a>
=> Update spec for rate limit window

report_verification.md
- Obsolete `fetch` integration
- Invalid property name
=> Fix JS issues in report_verification.md

EVENT.md
Updating pending sources per source origin limit
=> Update pending sources per source origin limit

app_to_web.md
=> Explainer change for supporting preferred platform for cross app web attribution

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1174.html" title="Last updated on Feb 28, 2024, 2:23 PM UTC (bb9c8a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1174/7481d1e...linnan-github:bb9c8a8.html" title="Last updated on Feb 28, 2024, 2:23 PM UTC (bb9c8a8)">Diff</a>
=> Reorganize cross app web algorithms

EVENT.md, app_to_web.md, index.bs, ts/src/header-validator/validate-info.test.ts, ts/src/header-validator/validate-info.ts
Fixes #801
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1180.html" title="Last updated on Feb 29, 2024, 2:07 PM UTC (39c49e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1180/6c86af5...linnan-github:39c49e3.html" title="Last updated on Feb 29, 2024, 2:07 PM UTC (39c49e3)">Diff</a>
=> Explainer and spec update for header errors debug reports

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1201.html" title="Last updated on Mar 19, 2024, 6:48 PM UTC (76d050d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1201/1b38e43...apasel422:76d050d.html" title="Last updated on Mar 19, 2024, 6:48 PM UTC (76d050d)">Diff</a>
=> Prevent shuffling in automation local testing mode

ts/package-lock.json, ts/package.json, ts/src/header-validator/event_level_report.test.ts, ts/src/header-validator/validate-json.ts
This will be used as the basis for an independent interop-test-output checker.
=> Add event-level report validator

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1239.html" title="Last updated on Apr 9, 2024, 7:23 PM UTC (75468e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1239/00505ad...apasel422:75468e2.html" title="Last updated on Apr 9, 2024, 7:23 PM UTC (75468e2)">Diff</a>
=> Add list of trigger-registration JSON keys

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
=> Validate trigger_data for defaulted trigger_data_matching

index.bs
Fixes #382
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1254.html" title="Last updated on Apr 18, 2024, 6:01 PM UTC (7dd4d37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1254/bbe4ccc...apasel422:7dd4d37.html" title="Last updated on Apr 18, 2024, 6:01 PM UTC (7dd4d37)">Diff</a>
=> Use referrer policy for background attributionsrc requests

ts/src/header-validator/index.html, ts/src/header-validator/index.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-eligible.ts, ts/src/header-validator/validate-info.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-os.ts
This allows users to see how omitted values are defaulted, and how adjusted values are clamped.
=> Show effective values in header validator

ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
These were temporarily disabled in #1149.
=> Restore inconsistent-aggregatable-key warnings

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1269.html" title="Last updated on May 3, 2024, 3:28 PM UTC (917e504)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1269/1a9478a...apasel422:917e504.html" title="Last updated on May 3, 2024, 3:28 PM UTC (917e504)">Diff</a>
=> Minor spec formatting improvements

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1271.html" title="Last updated on May 6, 2024, 1:30 PM UTC (fce0689)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1271/c92234e...linnan-github:fce0689.html" title="Last updated on May 6, 2024, 1:30 PM UTC (fce0689)">Diff</a>
=> Update trigger verification data type in algorithms

index.bs
Fixes #1273
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 8, 2024, 12:34 PM UTC)_.
<details>
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL]([object Object])
```
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" …
```
=> Initialize number of event-level reports

EVENT.md, app_to_web.md, index.bs
https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/344
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1280.html" title="Last updated on May 10, 2024, 12:13 PM UTC (dc34614)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1280/2381553...apasel422:dc34614.html" title="Last updated on May 10, 2024, 12:13 PM UTC (dc34614)">Diff</a>
=> Note that Attribution-Reporting-Support header may be greased

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1286.html" title="Last updated on May 17, 2024, 1:52 PM UTC (08360a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1286/4565ada...apasel422:08360a9.html" title="Last updated on May 17, 2024, 1:52 PM UTC (08360a9)">Diff</a>
=> Minor formatting fixes

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1296.html" title="Last updated on May 23, 2024, 2:36 PM UTC (b1db155)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1296/69bed9d...apasel422:b1db155.html" title="Last updated on May 23, 2024, 2:36 PM UTC (b1db155)">Diff</a>
=> Sort spec lists alphabetically for ease of use

attribution_scopes.md
Updating the Attribution Scopes explainer to correct when sources are deactivated
=> Update attribution_scopes.md - update to when sources are deactivated

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1312.html" title="Last updated on May 31, 2024, 6:14 PM UTC (60872db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1312/196c35d...apasel422:60872db.html" title="Last updated on May 31, 2024, 6:14 PM UTC (60872db)">Diff</a>
=> s/the opaque origin/an opaque origin/

ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate.ts
For reuse with structured headers.
=> Move JSON-irrelevant functions to separate file

ts/src/header-validator/validate-json.ts
In preparation for addressing #1321.
This contains no behavioral changes.
=> Make length checks explicit for arrays and sets

ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate.ts
For reuse with structured headers.
=> Lift JSON-irrelevant functions to separate file

AGGREGATE.md
=> Fix laplace formula

ts/src/header-validator/source.test.ts
In preparation for addressing #1321.
=> Add tests for source-side set sizes

ts/package-lock.json, ts/package.json, ts/src/flexible-event/main.ts
For better type-safety and ergonomics.
=> Replace command-line-args with ts-command-line-args

AGGREGATE.md
Updated table of contents with proper link for flexible contribution filtering IDs
=> Update AGGREGATE.md - update table of contents

ts/src/header-validator/source.test.ts, ts/src/vendor-specific-values.ts
https://chromium-review.googlesource.com/c/chromium/src/+/5593368
=> Update Chromium's max trigger-state cardinality

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
To match the spec.
Fixes #1321.
=> Check size of sets after deduplication instead of before

attribution_scopes.md, params/chromium-params.md
Updating the Privacy Considerations section to reflect the information gain checks
=> Update attribution_scopes.md - update privacy considerations

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1392.html" title="Last updated on Aug 14, 2024, 1:56 PM UTC (47364c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1392/d1fd7e5...linnan-github:47364c6.html" title="Last updated on Aug 14, 2024, 1:56 PM UTC (47364c6)">Diff</a>
=> Refactor source-destination-limit-replaced handling

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1393.html" title="Last updated on Aug 15, 2024, 3:35 PM UTC (bdaa078)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1393/1dbcd91...linnan-github:bdaa078.html" title="Last updated on Aug 15, 2024, 3:35 PM UTC (bdaa078)">Diff</a>
=> Remove unused algorithm for verbose debug reports

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1407.html" title="Last updated on Aug 29, 2024, 6:54 PM UTC (6b41d0d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1407/a9a53f5...apasel422:6b41d0d.html" title="Last updated on Aug 29, 2024, 6:54 PM UTC (6b41d0d)">Diff</a>
=> Clone selected scopes to avoid updating the source's persistent ones

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1410.html" title="Last updated on Sep 4, 2024, 2:05 PM UTC (7f1491e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1410/7772278...apasel422:7f1491e.html" title="Last updated on Sep 4, 2024, 2:05 PM UTC (7f1491e)">Diff</a>
=> Simplify scope-compatibility algorithm

index.bs
- Fix tuple references
- Destructure tuples where appropriate
- Fix headings for matching-source algorithms
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1417.html" title="Last updated on Sep 4, 2024, 6:07 PM UTC (d8aeb7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1417/d7cc5af...apasel422:d8aeb7e.html" title="Last updated on Sep 4, 2024, 6:07 PM UTC (d8aeb7e)">Diff</a>
=> Miscellaneous specification cleanup

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1418.html" title="Last updated on Sep 5, 2024, 3:26 PM UTC (5bf4877)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1418/b1a6dee...linnan-github:5bf4877.html" title="Last updated on Sep 5, 2024, 3:26 PM UTC (5bf4877)">Diff</a>
=> Add missing tuple reference

attribution_scopes.md
Also added a diagram for the flow.
=> Add source and trigger registration links for attribution scopes example

AGGREGATE.md
Updating table of contents to include Named Budgets feature
=> Update AGGREGATE.md Table of Contents

EVENT.md
=> Add <area> to explainer

flexible_event_config.md
=> Shrink Flex Event example from 6 report windows to 5

index.bs
Update to affiliation to Google LLC
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1481.html" title="Last updated on Dec 17, 2024, 6:43 PM UTC (ad756b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1481/99f0a26...ad756b5.html" title="Last updated on Dec 17, 2024, 6:43 PM UTC (ad756b5)">Diff</a>
=> Update affiliation to Google LLC

index.bs
Updated spec to include additional editors
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1483.html" title="Last updated on Dec 17, 2024, 7:21 PM UTC (02356f3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1483/c6e2c79...02356f3.html" title="Last updated on Dec 17, 2024, 7:21 PM UTC (02356f3)">Diff</a>
=> Add spec authors and alphabetize list

verbose_debugging_reports.md
Add authors to verbose debugging reports explainer
=> Add authors to verbose debugging reports explainer

AGGREGATION_SERVICE_TEE.md
Format authors section in aggregation service in TEE explainer to align with other files
=> Format authors section in aggregation service in TEE explainer

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1501.html" title="Last updated on Feb 26, 2025, 6:07 PM UTC (3250d1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1501/ed9eba3...apasel422:3250d1d.html" title="Last updated on Feb 26, 2025, 6:07 PM UTC (3250d1d)">Diff</a>
=> Replace stray colon with period

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1504.html" title="Last updated on Mar 6, 2025, 6:30 PM UTC (c3427ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1504/1dd2b08...linnan-github:c3427ae.html" title="Last updated on Mar 6, 2025, 6:30 PM UTC (c3427ae)">Diff</a>
=> fix spec build

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1526.html" title="Last updated on May 20, 2025, 1:09 PM UTC (a390215)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1526/f3bf8e8...apasel422:a390215.html" title="Last updated on May 20, 2025, 1:09 PM UTC (a390215)">Diff</a>
=> Rename Trigger Specs header
