WICG/attribution-reporting-api

README.md
This change replaces the `last-clicked` attribute in the explainer with `attribution_credit`, and provides some additional context this more flexible attribution model.
=> Change `last-clicked` to `attribution-credit`

README.md
Clarify in the reporting windows section that impression expiry can be used in place of the 7 day window.
=> Clarify reporting windows

README.md
In the last Web-Advertising Business Group call, there was some confusion over what the noise applied to — the 3 bits of conversion metadata, or the reporting of the conversion event itself.  Added a bit of clarifying text, so that someone who just sees one of the two noise sections is directed to the other one as well.
=> Clarify what the proposed "5% noise" applies to

README.md
Mention that the original frequencies can be recovered in aggregate (followup from issue #24 )
=> Mention randomized response in the metadata section

README.md
Removes main frame restriction on conversion registration in favor of FP controls, as described on #42
=> Use FP for controls on conversion registration

README.md
These are unnecessary and are sometimes incorrectly parsed by Chrome's implementation.
Fixes issue 61
=> Remove "0x" prefix on hex values

README.md
Chromium implements a 30 day default, and aligning max/default makes this a bit simpler to understand.
=> Update default `impressionexpiry` to 30 days

denoiser.py
Adds a simple python script that corrects noisy, aggregate bucket counts using an unbiased estimator.
Partially addresses the concerns in issue #24, to show that aggregate data can be estimated.
Follow-up work can outline a technique to reduce variance at the cost of adding bias.
=> Add denoiser.py

index.bs
The PR adds a few algorithms for how to create impression / conversion structs.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/58.html" title="Last updated on Oct 13, 2020, 10:40 PM UTC (aac21ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/58/50aeae6...aac21ab.html" title="Last updated on Oct 13, 2020, 10:40 PM UTC (aac21ab)">Diff</a>
=> Add a few more algorithms for impression / conversion construction

README.md
Adds a section denoting how to register impressions for window.open navigations per #77
=> Add extension for window.open impressions

README.md
There is an extraneous parenthesis in the example iframe tag.
=> Fix typo in iframe allow attribute

index.bs
Flagged by HTML validation from Bikeshed output
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/conversion-measurement-api/pull/105.html" title="Last updated on Feb 7, 2021, 12:20 AM UTC (a491cd1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/105/6aa65ec...nschonni:a491cd1.html" title="Last updated on Feb 7, 2021, 12:20 AM UTC (a491cd1)">Diff</a>
=> fix: UL to DL for definition list

README.md
This updates the proposed API with the naming changes discussed on #57.
This includes updating the reporting format to a JSON body with the new names
=> Remove "impression"/"conversion" from API surfaces

README.md
Changes the metadata formats to integers, as discussed on #60.
=> Remove hexadecimal encoding from data types

README.md
This aligns with https://github.com/privacycg/private-click-measurement/issues/59#issue-762861988, which indicates that we should use a path component which indicates these are being used for the Attribution Reporting API
=> Make well-known endpoints scoped to attribution-reporting

README.md
This updates the explainer with new naming as discussed on https://github.com/privacycg/private-click-measurement/pull/75#discussion_r593476675
=> Change "attributeon" naming to "attributiondestination"

README.md
This is currently written using left and right quotes, which aren't handled by the Permissions Policy spec given the definition of the 'src' keyword, https://w3c.github.io/webappsec-permissions-policy/#allowlists
=> Use straight quotes inside of allow attribute value

README.md, app_to_web.md
Updates the README and app to web explainer to have attributionsourceeventid be encoded as a string, as suggested on #123
=> Update attributionsourceeventid encoding

README.md, event_attribution_reporting.md
This updates the window.open overload to supply attribution reporting attributes in the features parameter, rather than in a new window.open overload per #130
=> Update window.open interface to use features parameter

index.bs
This updates the draft spec to include all changes which were landed to the explainer since it was last updated.
This includes:
- all naming changes on #103 and #121
- removal of hexadecimal encoding for data fields
- clarification on the value represented by a/attributiondestination
Algorithm definitions and variables are updated to reflect the new naming.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/131.html" title="Last updated on Apr 30, 2021, 7:11 PM UTC (32fbcc1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/131/6e542cc...32fbcc1.html" title="Last updated on Apr 30, 2021, 7:11 PM UTC (32fbcc1)">Diff</a>
=> Update spec to current explainer

app_to_web.md
This was changed in the top level readme on #121 and should remain consistent across all API environments
=> Use attributionDestination naming in app_to_web.md

event_attribution_reporting.md
"Attribution" is a fairly generic term. It seems more ideal to have the proposed window exposed interface match the API name to the extent possible.
=> Rename document.attribution to attributionReporting

AGGREGATE.md
APIs on the web should use camelCase for JavaScript properties, not snake_case: https://w3ctag.github.io/design-principles/#casing-rules
Also fixes one local variable. Fixes #145
=> Worklet return values should use camelCase, not snake_case

index.bs
Reverts WICG/conversion-measurement-api#141, this was merged accidentally instead of #140
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/151.html" title="Last updated on May 25, 2021, 6:18 PM UTC (2bfb433)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/151/98dbdac...2bfb433.html" title="Last updated on May 25, 2021, 6:18 PM UTC (2bfb433)">Diff</a>
=> Revert "Spec storage for attribution sources and reports"

index.bs
Includes the list of content attributes to add, and specifies that they must be reflected from the idl attributes as discussed on #133
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/140.html" title="Last updated on May 19, 2021, 5:26 PM UTC (079db6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/140/5c456e6...079db6f.html" title="Last updated on May 19, 2021, 5:26 PM UTC (079db6f)">Diff</a>
=> Update <a> element monkey patch with content attributes

index.bs
This PR adds logic for:
- passing an attribution source on a navigation originating from a link click
- validating that the attribution source attached to a navigation declares the correct destination
- logic for adding a source to the attribution source cache
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/156.html" title="Last updated on Jun 9, 2021, 8:47 PM UTC (f912bd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/156/0cda822...f912bd2.html" title="Last updated on Jun 9, 2021, 8:47 PM UTC (f912bd2)">Diff</a>
=> Add monkeypatches for navigation logic

index.bs
This priority is necessary to spec algorithms for handling conversion events, and the browser attribution logic
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/159.html" title="Last updated on Jun 23, 2021, 4:38 PM UTC (bb20ccd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/159/77abb8d...bb20ccd.html" title="Last updated on Jun 23, 2021, 4:38 PM UTC (bb20ccd)">Diff</a>
=> Spec declaration of attributionsourcepriority

index.bs
This PR specifies the following:
- fetch monkeypatch for handling attribution triggers and blocking attribution trigger redirects
- algorithm for choosing with source to attribute a trigger to
- generating a report for a source and trigger
This also reorganizes the algorithms section to be split by source/trigger algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/167.html" title="Last updated on Jul 8, 2021, 8:10 PM UTC (93ceac1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/167/e6c049b...93ceac1.html" title="Last updated on Jul 8, 2021, 8:10 PM UTC (93ceac1)">Diff</a>
=> Spec attribution triggering

event_attribution_reporting_views.md, index.bs
Most notably, add the `attributionSourcePriority` param.
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/attribution_source_params.idl;drc=7a48dde0857eccf6f61397a962c8532869b861f2
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/184.html" title="Last updated on Jul 15, 2021, 7:26 PM UTC (23823ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/184/1ef789c...apasel422:23823ae.html" title="Last updated on Jul 15, 2021, 7:26 PM UTC (23823ae)">Diff</a>
=> Add priority to AttributionSourceParams and fix IDL types

event_attribution_reporting_clicks.md, event_attribution_reporting_views.md
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/172.html" title="Last updated on Jul 12, 2021, 1:02 PM UTC (0c3b08f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/172/51de375...apasel422:0c3b08f.html" title="Last updated on Jul 12, 2021, 1:02 PM UTC (0c3b08f)">Diff</a>
=> Remove notion of credit from explainers

AGGREGATE.md
Fixes a few things:
* The function identifier isn't allowed inside a `class` declaration.
* Tidy up whitespace (sorry, couldn't resist)
* Call to `registerAggregateReporter` passed in incorrect class name
=> Fix mistakes in sample convert.js module

AGGREGATE.md
The click and event explainers, as well as the draft spec, specify `attributiondestination` as the name of this attribute.
=> Replace attributeon attribute with attributiondestination in aggregate explainer

event_attribution_reporting_views.md
Allows reporters to avoid encoding soruce type in the eventid
=> Add source_type to report JSON

index.bs
We will spec the JS API for registering event sources and noising of event sources in a followup.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/198.html" title="Last updated on Sep 1, 2021, 12:57 PM UTC (929999f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/198/32c049b...apasel422:929999f.html" title="Last updated on Sep 1, 2021, 12:57 PM UTC (929999f)">Diff</a>
=> Spec anchor-based view-through measurement

event_attribution_reporting_clicks.md, index.bs
Current implementation in Chrome uses `trigger-data` not `data`.
Ref https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/loader/frame_fetch_context.cc;l=906;drc=2618b478442164f50764871703afacf0a7776fee.
I'm not sure which is the right naming. If the name of `data` is right, please fix Chrome.
Fixes #168
***
<a href="https://pr-preview.s3.amazonaws.com/shigeki/conversion-measurement-api/pull/207.html" title="Last updated on Sep 8, 2021, 7:43 PM UTC (4fab270)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/207/f519bc0...shigeki:4fab270.html" title="Last updated on Sep 8, 2021, 7:43 PM UTC (4fab270)">Diff</a>
=> Fix query parameter name of trigger data

index.bs
To avoid ambiguity around timezones and leap seconds per https://github.com/WICG/conversion-measurement-api/pull/213#discussion_r717721154.
Fixes #236.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/237.html" title="Last updated on Sep 30, 2021, 8:10 PM UTC (71f3b0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/237/ef672a3...apasel422:71f3b0a.html" title="Last updated on Sep 30, 2021, 8:10 PM UTC (71f3b0a)">Diff</a>
=> Store source expiry as a duration instead of point in time

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/265.html" title="Last updated on Nov 3, 2021, 9:23 PM UTC (60f860a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/265/a276a3e...apasel422:60f860a.html" title="Last updated on Nov 3, 2021, 9:23 PM UTC (60f860a)">Diff</a>
=> Replace trigger origin with attribution destination and fix deletion logic

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/266.html" title="Last updated on Nov 5, 2021, 7:00 PM UTC (21a61bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/266/cabacc3...apasel422:21a61bd.html" title="Last updated on Nov 5, 2021, 7:00 PM UTC (21a61bd)">Diff</a>
=> Store event id and trigger data as integers, not strings

index.bs
When a source's attribution mode is "falsely", the current implementation immediately deactivates it, preventing the source from subsequently being selected during attribution, but since there is no concept of active vs. inactive in the spec, the spec instead skips adding such sources to the source cache entirely.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/251.html" title="Last updated on Nov 8, 2021, 7:38 PM UTC (05f60fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/251/004ca47...apasel422:05f60fe.html" title="Last updated on Nov 8, 2021, 7:38 PM UTC (05f60fe)">Diff</a>
=> Spec false report attribution mode

index.bs
Fixes #228
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/252.html" title="Last updated on Nov 11, 2021, 6:54 PM UTC (d00ade6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/252/3c7fb7b...apasel422:d00ade6.html" title="Last updated on Nov 11, 2021, 6:54 PM UTC (d00ade6)">Diff</a>
=> Spec report ID for deduplication in the event of retries on network errors

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/269.html" title="Last updated on Nov 18, 2021, 6:16 PM UTC (63c9256)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/269/5d63a03...apasel422:63c9256.html" title="Last updated on Nov 18, 2021, 6:16 PM UTC (63c9256)">Diff</a>
=> Replace erroneous reference to source reporting endpoint with trigger one

AGGREGATE.md
This aligns with the histogramContributions field in the worklet and grants additional flexibility in the design.
=> Allow multiple contributions in a single-server report

index.bs
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 6, 2022, 8:10 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fapasel422%2Fconversion-measurement-api%2Fd5960ff3fadb15c7f51c63d1950557cfd45699dd%2Findex.bs&force=1&md-warning=not%20ready)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The …
```
=> Reformulate noising as randomized responses

index.bs
Fixes #273.
- `randomized_trigger_data_rate`
- `randomized_trigger_rate`
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/274.html" title="Last updated on Jan 6, 2022, 8:39 PM UTC (8686a04)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/274/1ed40d1...apasel422:8686a04.html" title="Last updated on Jan 6, 2022, 8:39 PM UTC (8686a04)">Diff</a>
=> Add noise probabilities to report body

EVENT.md
Modify this feature to drop sources when at the limit, rather than maintaining a FIFO queue. This aligns behavior with reporting cooldowns/unique reporting origins.
=> Align pending destination limit with other limits

AGGREGATE.md
This change should be privacy neutral given the debug ids that are already present on the report, and it allows the reporting origin to verify the payload without depending on the aggregation service.
=> Add `debug_cleartext_payload` to aggregatable reports

EVENT.md
The probability is expressed as a value in the range [0, 1], not a percentage.
=> Use correct probability in report JSON

EVENT.md
The current filtering operates solely on equality comparisons. For this reason, there is not a string reason to support native integers as it complicates the schema both for developers and browsers.
This can be added back if a specific need arises.
=> Remove int value support from filters

EVENT.md
There's not a strong reason to support a single string as a shorthand of a list with one element, therefore proposing to remove the shorthand support to simplify the schema and implementation.
This can be added back if specific need arises.
=> Remove single string support from filters

AGGREGATE.md
Dealing with binary, while conceptually simpler, is practically more difficult to integrate with existing systems. Additionally, the ergonomics of having an existing "offset" parameter are arguably not worth it, as this can be easily achieved with bit-shifting operators during header generation.
Let's keep this API as simple as possible for now.
=> Just use hex for key_piece definition

AGGREGATE.md
Mention that if debugging is enabled, debug_mode=1 will be set in shared_info to indicate to a downstream aggregation service that it's OK to treat this report as a debug report.
=> Mention debug_mode flag in shared_info

AGGREGATE.md
Currently, 1 is used as a sentinel value, but an enum would allow us to support multiple options in the future if necessary.
=> Use an enum for debug_mode

EVENT.md
The entire registration JSON is arguably "source data", so let's make it clear that the contents of this field are specific to filtering.
=> Rename source_data to filter_data in source registration JSON

noise_corrector.py
This PR massively overhauls the noise corrector. It has turned into a fully fledged command line utility that takes as input JSON files of sources and reports.
Given JSON inputs of event-level sources and reports, It provides two types of outputs:
1. Aggregate output: The tool aggregates event-level reports and reports de-biased histograms broken out by the trigger_data, in an unbiased way.
2. Event-level output: The tool synthesizer adjusted event-level data to match (as best as possible) the de-biased aggregates
Fixes #301
Note this utility is designed to be interoperable with the JSON formats in the WIP [Chromium API simulator](https://source.chromium.org/chromium/chromium/src/+/main:tools/attribution_reporting/) in the following way:
```
+-----------+ +------------+
|Source JSON| …
```
=> Flesh out the noise corrector

EVENT.md
These fields are already contained in a source- or trigger-registration JSON document, so the `source_` and `trigger_` prefixes are redundant.
=> Remove redundant prefixes from source and trigger priority JSON fields

EVENT.md
Using a URL other than `.well-known/attribution-reporting/debug` is more extensible.
=> Use more specific URL for debug reports and clarify debug report bodies

EVENT.md
To clearly distinguish it from report-aggregatable-attribution.
=> Rename event-level report endpoint to report-event-attribution

AGGREGATE.md
This partially addresses #352 by ensuring that no information about each contribution is revealed through the length of the value's encoding.
=> Update value encoding to have a fixed length

EVENT.md
Removes the attributionsrc requirement for trigger registration, fixing #347
=> Resolve todo on supporting legacy conversion pings

EVENT.md
The methods are already on a property called `attributionReporting`.
=> Remove redundant Attribution infix from JS registration methods

EVENT.md
There is an existing TODO which speculates whether anchor tags supporting view source registration in addition to a click source is useful/necessary functionality.
This is naturally possible by instead including two separate tags:
```
<a href="..." attributionsrc="..register-click"></a>
```
The speculative API to register views on anchor tags involves adding a new attribute, and a new request header to allow sites to differentiate between duplicate requests to the same url.
It makes more sense to frame this TODO as an ask for whether this API should be supported, rather than including it by default.
=> Remove speculative <a> view API surface

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#reporting-cooldown--rate-limits
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/387.html" title="Last updated on Apr 27, 2022, 6:10 PM UTC (4d1014a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/387/c4231c8...apasel422:4d1014a.html" title="Last updated on Apr 27, 2022, 6:10 PM UTC (4d1014a)">Diff</a>
=> Replace attribution rate-limit source-type scope with reporting endpoint

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#reporting-origin-limits
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/391.html" title="Last updated on Apr 29, 2022, 5:07 PM UTC (7ef839f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/391/a079a70...apasel422:7ef839f.html" title="Last updated on Apr 29, 2022, 5:07 PM UTC (7ef839f)">Diff</a>
=> Specify distinct reporting-origin limits for attributions

index.bs
But do not set top-level trigger filters to anything but the empty map for now.
We will add negated filter matching in a followup, as top-level filters may only be positive.
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/389.html" title="Last updated on Apr 28, 2022, 2:02 PM UTC (e8e515a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/389/c4231c8...apasel422:e8e515a.html" title="Last updated on Apr 28, 2022, 2:02 PM UTC (e8e515a)">Diff</a>
=> Specify top-level filter matching

index.bs
If there is already a rate-limit record for a reporting endpoint, the new attribution should not add to the number of distinct origins.
This was a bug in #391.
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/392.html" title="Last updated on May 2, 2022, 4:42 PM UTC (55bdc4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/392/fd75741...apasel422:55bdc4e.html" title="Last updated on May 2, 2022, 4:42 PM UTC (55bdc4e)">Diff</a>
=> Fix rate-limiting of already-stored reporting endpoints

index.bs
It is used for both sources and triggers.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/395.html" title="Last updated on May 3, 2022, 1:30 PM UTC (fa8ba87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/395/a1536e8...apasel422:fa8ba87.html" title="Last updated on May 3, 2022, 1:30 PM UTC (fa8ba87)">Diff</a>
=> Move parse-attribution-data algorithm to general section

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/398.html" title="Last updated on May 3, 2022, 2:13 PM UTC (c9476c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/398/54a3a50...apasel422:c9476c8.html" title="Last updated on May 3, 2022, 2:13 PM UTC (c9476c8)">Diff</a>
=> Add shorthand for obtaining a source's source site

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#attribution-reports
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/403.html" title="Last updated on May 3, 2022, 6:24 PM UTC (6aa8f0d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/403/7ef99b5...apasel422:6aa8f0d.html" title="Last updated on May 3, 2022, 6:24 PM UTC (6aa8f0d)">Diff</a>
=> Replace report-attribution URL path with report-event-attribution

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#triggering-attribution
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/405.html" title="Last updated on May 3, 2022, 7:25 PM UTC (206a74e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/405/5644d23...apasel422:206a74e.html" title="Last updated on May 3, 2022, 7:25 PM UTC (206a74e)">Diff</a>
=> Allow max attributions per source to vary by source type

AGGREGATE.md
This may help with the regretful user user case so that there's a chance for the user to delete the attributions before they get sent.
=> Impose a minimum delay of 10 minutes for aggregatable reports

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#reporting-cooldown--rate-limits
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/394.html" title="Last updated on May 5, 2022, 8:39 PM UTC (b405cdb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/394/7ef99b5...apasel422:b405cdb.html" title="Last updated on May 5, 2022, 8:39 PM UTC (b405cdb)">Diff</a>
=> Specify reporting-origin limits for source registrations

index.bs
https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#optional-extended-debugging-reports
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/404.html" title="Last updated on May 6, 2022, 5:11 PM UTC (ef218b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/404/9db50a5...apasel422:ef218b0.html" title="Last updated on May 6, 2022, 5:11 PM UTC (ef218b0)">Diff</a>
=> Specify debug-report delivery

EVENT.md
This is JSON, so it only makes sense to talk about strings, not
DOMString.
=> Remove misleading use of DOMString from event explainer

index.bs
Spec the algorithm to create aggregatable histograms from attribution source and trigger. 
Note that filters logic depends on https://github.com/WICG/conversion-measurement-api/pull/402 and negated filters logic is not included yet and will be addressed later.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/416.html" title="Last updated on May 9, 2022, 6:30 PM UTC (2b45f48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/416/ae0fc40...2b45f48.html" title="Last updated on May 9, 2022, 6:30 PM UTC (2b45f48)">Diff</a>
=> Specify aggregatable histogram creation

index.bs
Since we will be enabling randomized responses for navigation sources in
a followup change, this simplifies the algorithm structure.
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/413.html" title="Last updated on May 10, 2022, 3:25 PM UTC (cddaf8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/413/f4e4f31...apasel422:cddaf8a.html" title="Last updated on May 10, 2022, 3:25 PM UTC (cddaf8a)">Diff</a>
=> Merge event-source-specific changes into general source algorithm

index.bs
We will spec this later on alongside the other attributionsrc surfaces.
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/424.html" title="Last updated on May 11, 2022, 1:38 PM UTC (ae7917a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/424/183c928...apasel422:ae7917a.html" title="Last updated on May 11, 2022, 1:38 PM UTC (ae7917a)">Diff</a>
=> Rename registerAttributionSource to registerSource and delete implementation

index.bs
This generalizes the spec overview to not focus on clicks / specific API surfaces given the number of different registration surfaces / report types currently in the explainer
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/427.html" title="Last updated on May 12, 2022, 5:46 PM UTC (9dea016)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/427/6c3dbed...9dea016.html" title="Last updated on May 12, 2022, 5:46 PM UTC (9dea016)">Diff</a>
=> Generalize overview of spec

EVENT.md
=> Replace dedicated JS registration APIs with generic mechanism via fetch

index.bs
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/429.html" title="Last updated on May 18, 2022, 1:26 PM UTC (4ef0ac8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/429/d97d600...apasel422:4ef0ac8.html" title="Last updated on May 18, 2022, 1:26 PM UTC (4ef0ac8)">Diff</a>
=> Remove window.attributionReporting.registerSource from spec

EVENT.md
Limits on trigger data are applied based on the type of the attributed source, which is discussed in the Data Limits section.
=> Remove erroneous data-limit comment from event explainer

index.bs
We add a rudimentary description of the new `attributionsrc` attribute, but will expound on it in followup PRs.
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/426.html" title="Last updated on May 24, 2022, 4:05 PM UTC (ad1314b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/426/0768be8...apasel422:ad1314b.html" title="Last updated on May 24, 2022, 4:05 PM UTC (ad1314b)">Diff</a>
=> Remove anchor-based source-registration from spec

index.bs
There's no change to the algorithm yet, just renaming.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/pull/410.html" title="Last updated on May 25, 2022, 3:49 AM UTC (10f04d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/conversion-measurement-api/410/f7e28e9...10f04d0.html" title="Last updated on May 25, 2022, 3:49 AM UTC (10f04d0)">Diff</a>
=> Rename attribution report to event-level attribution report

index.bs
This name is more clear, and aligns with #434.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/456.html" title="Last updated on May 26, 2022, 5:55 PM UTC (5df731d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/456/d2e33b2...apasel422:5df731d.html" title="Last updated on May 26, 2022, 5:55 PM UTC (5df731d)">Diff</a>
=> Rename "aggregatable source" to "aggregation keys"

AGGREGATE.md, EVENT.md
This improves the utility of the API for reporting origins that are only interested in aggregatable reports, reducing unnecessary local storage and bandwidth.
=> Make event-trigger registration optional

index.bs
And update it to use JSON parsing.
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/conversion-measurement-api/pull/451.html" title="Last updated on May 26, 2022, 6:29 PM UTC (a43f3ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/451/d2e33b2...apasel422:a43f3ef.html" title="Last updated on May 26, 2022, 6:29 PM UTC (a43f3ef)">Diff</a>
=> Remove redirect-based trigger-registration API surface

EVENT.md
Resolves https://github.com/WICG/conversion-measurement-api/issues/446
=> Allow script elements to use attribution

index.bs
It should be 'self', not *, since we do not automatically allow the feature in cross origin contexts.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/463.html" title="Last updated on May 31, 2022, 4:22 PM UTC (ce45257)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/463/3e365fb...ce45257.html" title="Last updated on May 31, 2022, 4:22 PM UTC (ce45257)">Diff</a>
=> Update Permissions Policy default allowlist

index.bs
The spec currently uses histogram to refer to a single key value pair which is misleading, as the expectation is many of these objects make up a histogram.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/466.html" title="Last updated on May 31, 2022, 8:47 PM UTC (f9ef137)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/466/853b7a2...f9ef137.html" title="Last updated on May 31, 2022, 8:47 PM UTC (f9ef137)">Diff</a>
=> Use contribution in place of histogram in the spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/469.html" title="Last updated on Jun 1, 2022, 3:37 PM UTC (188f1c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/469/40bfa3a...188f1c6.html" title="Last updated on Jun 1, 2022, 3:37 PM UTC (188f1c6)">Diff</a>
=> Link to map setters in spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/475.html" title="Last updated on Jun 3, 2022, 2:46 PM UTC (fc98986)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/475/6d3b06c...fc98986.html" title="Last updated on Jun 3, 2022, 2:46 PM UTC (fc98986)">Diff</a>
=> Use same origin instead of equals 

index.bs
Note: this leaves an open issue after parsing the `attributionsrc` string similar to the anchor registration.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/476.html" title="Last updated on Jun 6, 2022, 3:37 PM UTC (757d4b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/476/6d3b06c...757d4b1.html" title="Last updated on Jun 6, 2022, 3:37 PM UTC (757d4b1)">Diff</a>
=> Specify window.open monkeypatch

AGGREGATE.md
Fixes https://github.com/WICG/attribution-reporting-api/issues/365 and simplifies the aggregatable report.
- sorts the keys in ascending lexicographic order
- moves the attribution_destination and source_registration_time keys into shared_info
=> Remove privacy_budget_key

index.bs
It's unclear how best to reference the cookie standard, so for now we always block debug-key setting.
#386
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/479.html" title="Last updated on Jun 7, 2022, 4:23 PM UTC (8c20e43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/479/8ee7e65...apasel422:8c20e43.html" title="Last updated on Jun 7, 2022, 4:23 PM UTC (8c20e43)">Diff</a>
=> Add stub specification for debug-key cookie checks

AGGREGATE.md
Allows for the aggregation service to support multiple APIs in the future
=> Add "api" string enum field to shared info

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/435.html" title="Last updated on Jun 2, 2022, 3:18 PM UTC (3f9b00f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/435/9e434cb...3f9b00f.html" title="Last updated on Jun 2, 2022, 3:18 PM UTC (3f9b00f)">Diff</a>
=> Specify negated filters for event-level and aggregate attribution

validate-json.mjs
The former is a string, the latter an object.
Fixes #497
=> Check url.search instead of url.searchParams

header-validator/README.md, header-validator/index.js, header-validator/package.json
Fixes #495 
To test, run `node ./index.js` in the header-validator folder. ⚠️ Merge https://github.com/WICG/attribution-reporting-api/pull/502 first.
This tests all possible failure cases the validator supports; filter testing is a bit light for now, we could expand later.
=> Added source headers to test the validator

EVENT.md, header-validator/data.source.js, header-validator/validate-json.js, index.bs
This simplifies source registration for users of the API who only care about aggregatable reports, for which the source_event_id value is irrelevant.
Fixes #517
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/518.html" title="Last updated on Jul 26, 2022, 1:48 PM UTC (983ad9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/518/9bbe9bd...apasel422:983ad9a.html" title="Last updated on Jul 26, 2022, 1:48 PM UTC (983ad9a)">Diff</a>
=> Make source_event_id field optional

app_to_web.md
Commas are used to separate dictionary members, not semi-colons, and per
the spec, values of true (`=?1`) are omitted when serialized.
=> Fix syntax of Attribution-Reporting-Support header

header-validator/validate-json.js, index.bs
The [explainer](https://github.com/WICG/attribution-reporting-api/blob/608e6da694849b1c07d297b54009b02ca9385a29/EVENT.md?plain=1#L296) already indicates that this field is optional, and this spec change aligns this field with the behavior of `source_event_id` in #518.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/542.html" title="Last updated on Aug 16, 2022, 3:09 PM UTC (f0e70fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/542/608e6da...apasel422:f0e70fd.html" title="Last updated on Aug 16, 2022, 3:09 PM UTC (f0e70fd)">Diff</a>
=> Default event_trigger_data to 0 if omitted or it has the wrong type

EVENT.md, index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/551.html" title="Last updated on Sep 7, 2022, 2:22 PM UTC (70c2a16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/551/ea62c4a...70c2a16.html" title="Last updated on Sep 7, 2022, 2:22 PM UTC (70c2a16)">Diff</a>
=> Note that the Permission Policy has default * for the Chromium OT

EVENT.md
=> Clarify that ar_debug cookie must be unpartitioned

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/581.html" title="Last updated on Oct 11, 2022, 12:00 AM UTC (741acc9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/581/014cdac...741acc9.html" title="Last updated on Oct 11, 2022, 12:00 AM UTC (741acc9)">Diff</a>
=> Fixed typo in aggregatable histogram creation spec

EVENT.md
Also make it clear that source_site is omitted if the source is registered inside a fenced frame tree.
=> Change error reports to verbose debug reports to be more general

index.bs
Introduce aggregatable attribution report struct and spec the algorithm to trigger aggregatable attribution.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/423.html" title="Last updated on Oct 17, 2022, 5:31 PM UTC (99b40f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/423/737c5cd...99b40f7.html" title="Last updated on Oct 17, 2022, 5:31 PM UTC (99b40f7)">Diff</a>
=> Specify aggregatable report triggering algorithm

app_to_web.md
The current language is vague and can be interpreted in two ways.
=> Clarify language on bad OS response headers

EVENT.md, index.bs
Fixes #590
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/592.html" title="Last updated on Oct 26, 2022, 9:07 PM UTC (d844202)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/592/0b4ce8a...d844202.html" title="Last updated on Oct 26, 2022, 9:07 PM UTC (d844202)">Diff</a>
=> Remove landing page restriction for navigation sources

EVENT.md
Per https://github.com/WICG/attribution-reporting-api/issues/590, this is no longer necessary
=> Allow different destinations for navigation sources in a redirect chain

index.bs
FIxed #580
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/594.html" title="Last updated on Oct 27, 2022, 2:53 AM UTC (417547f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/594/ad74087...417547f.html" title="Last updated on Oct 27, 2022, 2:53 AM UTC (417547f)">Diff</a>
=> Adjust early deadlines

EVENT.md, header-validator/data.source.js, header-validator/validate-json.js, index.bs
Fixes #44 as far as I can tell. This PR attempts to be a fully backwards compatible change, so existing deployments will not have to update any code to accomodate.
Addresses #549, not calling it fixed until further verification.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/601.html" title="Last updated on Nov 7, 2022, 6:32 PM UTC (f9ac370)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/601/2db4718...f9ac370.html" title="Last updated on Nov 7, 2022, 6:32 PM UTC (f9ac370)">Diff</a>
=> Update explainer and spec to support multiple destinations

index.bs
This was an oversight in #577.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/609.html" title="Last updated on Nov 9, 2022, 7:00 PM UTC (8808fbe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/609/d33f461...apasel422:8808fbe.html" title="Last updated on Nov 9, 2022, 7:00 PM UTC (8808fbe)">Diff</a>
=> Return `dropped` when report window has expired

header-validator/test.eligible.js
This allows the test cases to be validated programatically instead of via manual inspection of log output.
I will do the same for the other tests in followup PRs.
=> Use assertions in Eligible header validation instead of log output

index.bs
After discussion with @johnivdel, report windows should be guaranteed to be less than or equal to expiry. If the report window time(s) provided are greater than the expiry time, the report window will be clamped to expiry.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/610.html" title="Last updated on Nov 9, 2022, 8:48 PM UTC (6c17e70)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/610/14b657c...6c17e70.html" title="Last updated on Nov 9, 2022, 8:48 PM UTC (6c17e70)">Diff</a>
=> Bound report windows by expiry time

index.bs
This doesn't currently cover the token issuance steps at request time. Those will require fetch monkey patches.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/616.html" title="Last updated on Nov 14, 2022, 9:36 PM UTC (963007e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/616/1d5f4b7...963007e.html" title="Last updated on Nov 14, 2022, 9:36 PM UTC (963007e)">Diff</a>
=> Spec trigger attestation

index.bs
Spec debug reports for the following errors common to event-level and aggregatable reports.
* No matching top-level filter data.
* Attributions rate-limit reached.
* Reporting origin rate-limit reached.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/628.html" title="Last updated on Nov 22, 2022, 7:53 PM UTC (c9336ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/628/05918d1...c9336ab.html" title="Last updated on Nov 22, 2022, 7:53 PM UTC (c9336ab)">Diff</a>
=> Spec debug reports for common trigger errors

index.bs
Only one use of this algorithm supplies "source" for that parameter, so it's simpler to just check the lone requirement for source filter data there rather than require all callers to supply the registrationType parameter.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/631.html" title="Last updated on Nov 23, 2022, 2:00 PM UTC (a06ef62)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/631/3e5d1db...apasel422:a06ef62.html" title="Last updated on Nov 23, 2022, 2:00 PM UTC (a06ef62)">Diff</a>
=> Remove registrationType parameter from "parse filter data" algorithm

AGGREGATE.md
This is only needed at trigger time.
=> Move aggregation_mode to trigger registration

EVENT.md, verbose_debugging_reports.md
The reporting origin doesn't always be attributionsrc origin.
=> Use reporting origin instead of attributionsrc origin for source matching

AGGREGATE.md, EVENT.md, verbose_debugging_reports.md
This is to avoid confusion with the two types of debugging reports.
=> Group attribution-success and verbose debugging reports under transitional debugging reports

index.bs
The algorithm changes for checking unexpired destination limit from #601 includes appending the new source's destinations with the set holding the currently stored destinations when checking if the size has surpassed the max destinations per source site. Previously, the new source's destination was never appended to this set, so it made sense to have the set's size check be greater than or equal to the max limit, but now it makes more sense to make the condition just greater than.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/650.html" title="Last updated on Dec 15, 2022, 1:35 PM UTC (0259ad7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/650/14b657c...0259ad7.html" title="Last updated on Dec 15, 2022, …
=> Fix unexpired destinations limit return to handle new algorithm

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/658.html" title="Last updated on Dec 22, 2022, 5:50 PM UTC (0f77299)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/658/f6846bb...apasel422:0f77299.html" title="Last updated on Dec 22, 2022, 5:50 PM UTC (0f77299)">Diff</a>
=> Add helper for matching both filters and negated filters

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/663.html" title="Last updated on Jan 9, 2023, 1:31 PM UTC (97cde5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/663/29823c2...apasel422:97cde5a.html" title="Last updated on Jan 9, 2023, 1:31 PM UTC (97cde5a)">Diff</a>
=> Reference report time field in report-delivery algorithm

index.bs
Broken by https://github.com/w3c/webappsec-permissions-policy/pull/498.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/668.html" title="Last updated on Jan 12, 2023, 5:28 PM UTC (2d769ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/668/d727ea7...apasel422:2d769ce.html" title="Last updated on Jan 12, 2023, 5:28 PM UTC (2d769ce)">Diff</a>
=> Fix broken default allowlist links

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/673.html" title="Last updated on Jan 18, 2023, 3:19 PM UTC (85102c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/673/5e102d4...apasel422:85102c1.html" title="Last updated on Jan 18, 2023, 3:19 PM UTC (85102c1)">Diff</a>
=> Replace erroneous map-iteration links with set iteration

index.bs
The scheme checks are already performed by the "parse an attribution destination" algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/674.html" title="Last updated on Jan 18, 2023, 3:55 PM UTC (6e07b1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/674/57375df...apasel422:6e07b1d.html" title="Last updated on Jan 18, 2023, 3:55 PM UTC (6e07b1d)">Diff</a>
=> Remove obsolete scheme issue

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/681.html" title="Last updated on Jan 20, 2023, 7:50 PM UTC (14a659b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/681/04f842a...linnan-github:14a659b.html" title="Last updated on Jan 20, 2023, 7:50 PM UTC (14a659b)">Diff</a>
=> Use source time for attribution rate limit

index.bs
Fixes #680
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/682.html" title="Last updated on Jan 20, 2023, 9:10 PM UTC (f684008)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/682/9214d1e...apasel422:f684008.html" title="Last updated on Jan 20, 2023, 9:10 PM UTC (f684008)">Diff</a>
=> Skip verbose debug report if no event-level trigger data is provided

index.bs
`set/empty` refers to the algorithm that clears a set.
`set/is empty` refers to the algorithm that checks if a set has no elements.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/683.html" title="Last updated on Jan 23, 2023, 2:15 PM UTC (6228d00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/683/eb1283d...apasel422:6228d00.html" title="Last updated on Jan 23, 2023, 2:15 PM UTC (6228d00)">Diff</a>
=> Fix erroneous set/empty links

index.bs
Instead of checking it in both event-level attribution and aggregatable attribution.
Note that this has an effect on which verbose debug report is sent, but arguably top-level filter matching should have priority, as if there is no matching source, attribution cannot proceed.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/684.html" title="Last updated on Jan 23, 2023, 2:56 PM UTC (95ffdb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/684/f9a0edc...apasel422:95ffdb4.html" title="Last updated on Jan 23, 2023, 2:56 PM UTC (95ffdb4)">Diff</a>
=> Extract common check for top-level filter matching

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/686.html" title="Last updated on Jan 23, 2023, 6:32 PM UTC (9b37b19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/686/437301c...apasel422:9b37b19.html" title="Last updated on Jan 23, 2023, 6:32 PM UTC (9b37b19)">Diff</a>
=> Return early and skip verbose debug reports if trigger has no data

index.bs
Since the logic is the same for both event-level and aggregatable.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/688.html" title="Last updated on Jan 24, 2023, 2:57 PM UTC (66cc92f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/688/cc8812c...apasel422:66cc92f.html" title="Last updated on Jan 24, 2023, 2:57 PM UTC (66cc92f)">Diff</a>
=> Extract algorithm for checking both rate limits during attribution

index.bs
The `continue` isn't that useful.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/695.html" title="Last updated on Feb 3, 2023, 1:53 PM UTC (edc82df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/695/53a4020...linnan-github:edc82df.html" title="Last updated on Feb 3, 2023, 1:53 PM UTC (edc82df)">Diff</a>
=> Simplify event level configuration matching algorithm

index.bs
[The Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/attribution_reporting/aggregatable_attribution_utils.cc;l=152;drc=0f570d2cac14c50891a3369be2b88f5678ec96c2) uses an underscore, not a space.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/697.html" title="Last updated on Feb 8, 2023, 6:03 PM UTC (2b700c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/697/95753e4...apasel422:2b700c0.html" title="Last updated on Feb 8, 2023, 6:03 PM UTC (2b700c0)">Diff</a>
=> Fix typo in attribution_destination shared info field

AGGREGATE.md, header-validator/data.trigger.js, header-validator/validate-json.js, index.bs
Fixes #664
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/692.html" title="Last updated on Feb 2, 2023, 11:28 PM UTC (b9f3cad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/692/75a7c8e...linnan-github:b9f3cad.html" title="Last updated on Feb 2, 2023, 11:28 PM UTC (b9f3cad)">Diff</a>
=> Filter-based aggregatable deduplication

EVENT.md
Adding a quite detailed explanation of the enumeration of the output states, including a short intro to the stars and bars method. Slightly verbose, and it could be well shortened if needed.
=> Explanation of the enumeration of the output states

index.bs
If deduplicated, should not attempt to create aggregatable contributions.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/699.html" title="Last updated on Feb 10, 2023, 2:49 PM UTC (9cabc96)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/699/87d93cc...linnan-github:9cabc96.html" title="Last updated on Feb 10, 2023, 2:49 PM UTC (9cabc96)">Diff</a>
=> Move aggregatable deduplication check earlier

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/704.html" title="Last updated on Feb 15, 2023, 2:25 PM UTC (0fb46d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/704/9990e3d...apasel422:0fb46d0.html" title="Last updated on Feb 15, 2023, 2:25 PM UTC (0fb46d0)">Diff</a>
=> Fix broken reference to current wall time

index.bs, verbose_debugging_reports.md
Source success verbose debug report will be sent when the source is registered successfully and when the unattributed reporting origin limit is hit to mitigate security concerns on reporting that error.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/706.html" title="Last updated on Feb 22, 2023, 2:47 PM UTC (4e01204)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/706/4691370...linnan-github:4e01204.html" title="Last updated on Feb 22, 2023, 2:47 PM UTC (4e01204)">Diff</a>
=> source-success verbose debug report

index.bs
It is unused in the implementation and merely complicates things.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/711.html" title="Last updated on Feb 27, 2023, 10:32 PM UTC (dc16561)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/711/bca95e1...apasel422:dc16561.html" title="Last updated on Feb 27, 2023, 10:32 PM UTC (dc16561)">Diff</a>
=> Remove concept of source event ID cardinality

EVENT.md, index.bs
Fixes #558
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/713.html" title="Last updated on Mar 1, 2023, 6:17 PM UTC (d478835)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/713/2c4e41d...d478835.html" title="Last updated on Mar 1, 2023, 6:17 PM UTC (d478835)">Diff</a>
=> Update default permission policy

AGGREGATION_SERVICE_TEE.md
The current comment does not reflect the actual output size. Here I update it to avoid confusion.
=> Fix the comment about the output size of the add_noise procedure.

AGGREGATE.md, index.bs
This may be used by ad-techs during cloud migration.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/728.html" title="Last updated on Mar 23, 2023, 6:37 PM UTC (d470398)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/728/f371279...linnan-github:d470398.html" title="Last updated on Mar 23, 2023, 6:37 PM UTC (d470398)">Diff</a>
=> Add aggregation coordinator identifier to aggregatable report

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/741.html" title="Last updated on Mar 29, 2023, 6:54 PM UTC (e71cb72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/741/0644ba0...e71cb72.html" title="Last updated on Mar 29, 2023, 6:54 PM UTC (e71cb72)">Diff</a>
=> Configure randomized response in terms of epsilon

EVENT.md
We use spaces due to the precedent from `<a ping>`. We will determine the syntax for `window.open` separately.
Fixes #718
=> Allow all HTML attributionsrc surfaces to make multiple background requests

EVENT.md
Since we have to monkeypatch window.open's feature-tokenization anyway in order to retain the original case of the URL, we allow the feature to appear multiple times and be accumulated into a list instead of using only the last instance.
#748
=> Describe multiple-background-request syntax for window.open attributionsrc

index.bs
Without this, the handling of untrustworthy origins within a redirect chain is inconsistent: The initial request is never made if the first URL is untrustworthy, but intermediate untrustworthy origins are silently ignored.
Note that we still require an origin to be trustworthy in order for its registrations to be processed; this just affects whether any request is made to untrustworthy ones.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/755.html" title="Last updated on Apr 11, 2023, 4:20 PM UTC (775df4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/755/814f787...apasel422:775df4f.html" title="Last updated on Apr 11, 2023, 4:20 PM UTC (775df4f)">Diff</a>
=> Allow attributionsrc requests to be made to untrustworthy origins

index.bs
The attribute already has no effect in insecure contexts, but with this IDL change it won't even exist in the DOM in insecure contexts, which makes feature-detection more precise via `'attributionSrc' in HTMLImageElement.prototype`.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/759.html" title="Last updated on Apr 14, 2023, 2:34 PM UTC (513567c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/759/8993abb...apasel422:513567c.html" title="Last updated on Apr 14, 2023, 2:34 PM UTC (513567c)">Diff</a>
=> Restrict attributionSrc HTML attribute to secure contexts

index.bs
Fixes #748
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/761.html" title="Last updated on Apr 14, 2023, 7:34 PM UTC (f277697)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/761/e7d6d7d...apasel422:f277697.html" title="Last updated on Apr 14, 2023, 7:34 PM UTC (f277697)">Diff</a>
=> Specify parsing for window.open attributionsrc feature

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/763.html" title="Last updated on Apr 17, 2023, 1:25 PM UTC (b01b88c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/763/b7263ac...apasel422:b01b88c.html" title="Last updated on Apr 17, 2023, 1:25 PM UTC (b01b88c)">Diff</a>
=> Add issue for setting Attribution-Reporting-Eligible header on img/script

app_to_web.md, header-validator/data.trigger.js, header-validator/validate-json.js, index.bs
Fixes #738
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/750.html" title="Last updated on Apr 18, 2023, 8:36 PM UTC (ee06ea5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/750/733c2f5...linnan-github:ee06ea5.html" title="Last updated on Apr 18, 2023, 8:36 PM UTC (ee06ea5)">Diff</a>
=> Spec for introducing null reports and source registration time configuration

index.bs
Fixes https://github.com/WICG/attribution-reporting-api/issues/734. Will still need to check complexity on the implementation side but I think this should fully specify the FR.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/742.html" title="Last updated on Mar 29, 2023, 9:43 PM UTC (95b8d3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/742/fe171ff...95b8d3a.html" title="Last updated on Mar 29, 2023, 9:43 PM UTC (95b8d3a)">Diff</a>
=> Flex windows

app_to_web.md, index.bs
Web attribution may not be supported on some platforms, e.g. WebView, which may be useful to be indicated in the Attribution-Reporting-Support header.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/758.html" title="Last updated on Apr 24, 2023, 3:34 PM UTC (22572a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/758/11466a5...linnan-github:22572a3.html" title="Last updated on Apr 24, 2023, 3:34 PM UTC (22572a3)">Diff</a>
=> Update explainer and spec to allow Attribution-Reporting-Support to indicate no web support

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/781.html" title="Last updated on May 5, 2023, 12:26 PM UTC (3461290)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/781/0ce6de7...apasel422:3461290.html" title="Last updated on May 5, 2023, 12:26 PM UTC (3461290)">Diff</a>
=> Add links to Structured Headers RFC

app_to_web.md, header-validator/test.os.js, header-validator/validate-os.js, index.bs
This does not add any new functionality to the API, as reporting origins could already redirect to another URL under their control in order to perform multiple registrations, but does obviate that bandwidth-wasting anti-pattern.
Fixes #696
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/780.html" title="Last updated on May 5, 2023, 1:58 PM UTC (9986dc2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/780/8c8e8a0...apasel422:9986dc2.html" title="Last updated on May 5, 2023, 1:58 PM UTC (9986dc2)">Diff</a>
=> Allow OS registration headers to specify multiple URLs

header-validator/validate-json.js, index.bs, verbose_debugging_reports.md
Spec for https://github.com/WICG/attribution-reporting-api/pull/774
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/778.html" title="Last updated on May 3, 2023, 7:51 PM UTC (6b5c895)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/778/c83fa51...linnan-github:6b5c895.html" title="Last updated on May 3, 2023, 7:51 PM UTC (6b5c895)">Diff</a>
=> Specify limiting number of aggregatable reports per source

index.bs
For consistency within the draft spec and implementation, and to distinguish from reporting sites.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/788.html" title="Last updated on May 10, 2023, 4:48 PM UTC (4d6b2c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/788/9044fce...apasel422:4d6b2c4.html" title="Last updated on May 10, 2023, 4:48 PM UTC (4d6b2c4)">Diff</a>
=> Rename reporting endpoint to reporting origin

index.bs
Instead of omitting the field, a default value 0 will be set for this field.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/790.html" title="Last updated on May 12, 2023, 12:00 PM UTC (495f499)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/790/2aa8f51...linnan-github:495f499.html" title="Last updated on May 12, 2023, 12:00 PM UTC (495f499)">Diff</a>
=> Set source_registration_time to 0 if it's excluded

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/815.html" title="Last updated on May 17, 2023, 7:31 PM UTC (c0d634e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/815/7ef1f9b...apasel422:c0d634e.html" title="Last updated on May 17, 2023, 7:31 PM UTC (c0d634e)">Diff</a>
=> Allow Attribution-Reporting-Eligible header to be greased

index.bs
We retain the not- prefix to grease the dictionary keys, but use the real keys to grease the dictionary values and parameters to ensure that only the keys are interpreted by the recipient, not the values or parameters. Removing the not- prefix in these contexts makes it less likely for naive string operations to "work".
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/818.html" title="Last updated on May 18, 2023, 1:07 PM UTC (4849dd8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/818/4b138b0...apasel422:4849dd8.html" title="Last updated on May 18, 2023, 1:07 PM UTC (4849dd8)">Diff</a>
=> Remove not- prefix from greased values and parameters

EVENT.md
=> Update max destinations covered by unexpired sources and max attributions per rate limit window limits to be per-site

index.bs
Note that this spec doesn't quite match up with the Chromium implementation, which just keeps everything in memory (and doesn't look at things like expiry). Still, with the window short enough it shouldn't make a large difference.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/819.html" title="Last updated on May 19, 2023, 10:40 PM UTC (4937df1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/819/0e687a2...4937df1.html" title="Last updated on May 19, 2023, 10:40 PM UTC (4937df1)">Diff</a>
=> Spec destination rate-limits

index.bs
This obsoletes #547. The consequences for this change is that the report request will fail if it redirects across origins.
Fixes #546.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/817.html" title="Last updated on May 18, 2023, 2:00 AM UTC (71d3942)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/817/4b138b0...71d3942.html" title="Last updated on May 18, 2023, 2:00 AM UTC (71d3942)">Diff</a>
=> Set report requests to be 'same-origin'

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/823.html" title="Last updated on May 23, 2023, 5:17 PM UTC (bdb246e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/823/8b9c5b7...linnan-github:bdb246e.html" title="Last updated on May 23, 2023, 5:17 PM UTC (bdb246e)">Diff</a>
=> Fix typo for setting report url path

EVENT.md
Fixes #822. A follow-up should do this for the `Support` header when that is spec'd.
=> Add GREASE to EVENT.md

index.bs
Goal is to mitigate a race condition where a user clicks on an ad which initiates a source registration and navigates to a page that initiates a trigger registration that matches the source. 
If the trigger registration completes before the source, the attribution would be dropped.
***
<a href="https://pr-preview.s3.amazonaws.com/agarant/attribution-reporting-api/pull/784.html" title="Last updated on May 30, 2023, 2:19 PM UTC (a7967b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/784/9debabb...agarant:a7967b5.html" title="Last updated on May 30, 2023, 2:19 PM UTC (a7967b5)">Diff</a>
=> Specify defer trigger attribution logic

index.bs
Fixes #805
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/826.html" title="Last updated on May 30, 2023, 3:29 PM UTC (18b61f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/826/0e16b7f...apasel422:18b61f1.html" title="Last updated on May 30, 2023, 3:29 PM UTC (18b61f1)">Diff</a>
=> Move "make background attributionsrc requests" out of HTML monkeypatches

index.bs
And instead, reject the registration entirely:
Sources:
1. `source_event_id`
2. `priority`
3. `expiry` (out-of-range values are still silently clamped)
4. `event_report_window` (out-of-range values are still silently clamped)
5. `aggregatable_report_window` (out-of-range values are still silently clamped)
Triggers:
1. event-level `trigger_data`
2. event-level `deduplication_key`
6. event-level `priority`
7. aggregatable `deduplication_key`
Other fields will be considered in a followup.
#793
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/825.html" title="Last updated on May 31, 2023, 12:51 PM UTC (1bf3d61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/825/0dece23...apasel422:1bf3d61.html" title="Last …
=> Remove silent defaults for certain source and trigger registration fields

AGGREGATE.md, header-validator/data.trigger.js, header-validator/validate-json.js, index.bs, schema/trigger.schema.json
To avoid a translation layer of vendor-specific identifier to origin.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/829.html" title="Last updated on May 31, 2023, 1:54 PM UTC (7cf1bde)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/829/93010b0...linnan-github:7cf1bde.html" title="Last updated on May 31, 2023, 1:54 PM UTC (7cf1bde)">Diff</a>
=> Use aggregation coordinator origin instead of identifier

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/832.html" title="Last updated on Jun 2, 2023, 3:18 PM UTC (386c6c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/832/138c8b0...linnan-github:386c6c2.html" title="Last updated on Jun 2, 2023, 3:18 PM UTC (386c6c2)">Diff</a>
=> Add same-origin policy considerations for debug reports

index.bs
Such that attribution success debug reports are 1-1 correspondence with the actual reports.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/840.html" title="Last updated on Jun 8, 2023, 5:23 PM UTC (01a8184)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/840/2ddc02b...linnan-github:01a8184.html" title="Last updated on Jun 8, 2023, 5:23 PM UTC (01a8184)">Diff</a>
=> Update the spec to not sending attribution success debug reports if reports are dropped for noise

index.bs
Similar to rate limits, fake reports will contribute to the storage limit but not check it before storage.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/836.html" title="Last updated on Jun 8, 2023, 3:26 PM UTC (843bec7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/836/59892b2...linnan-github:843bec7.html" title="Last updated on Jun 8, 2023, 3:26 PM UTC (843bec7)">Diff</a>
=> Remove issue for fake reports with storage limit

EVENT.md
https://wicg.github.io/attribution-reporting-api/#max-source-reporting-origins-per-source-reporting-site
=> Source throttling on destinations is per reporting site

index.bs
This PR should not induce any behavior change. It just restructures things so that follow-up spec changes can be made to more easily pre-configure reporting windows associated with individual sources.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/855.html" title="Last updated on Jun 22, 2023, 1:56 PM UTC (d0d7065)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/855/b631440...d0d7065.html" title="Last updated on Jun 22, 2023, 1:56 PM UTC (d0d7065)">Diff</a>
=> Refactor event-level reporting windows

index.bs
The implementation uses base::Time::Now() which doesn't consider cross origin isolated contexts as well.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/858.html" title="Last updated on Jun 22, 2023, 12:53 PM UTC (451d320)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/858/d91215b...linnan-github:451d320.html" title="Last updated on Jun 22, 2023, 12:53 PM UTC (451d320)">Diff</a>
=> Use current wall time instead of the one on environment settings object

index.bs
The error condition from "parse an attribution destination" was being improperly ignored.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/860.html" title="Last updated on Jun 22, 2023, 6:06 PM UTC (bf3a1bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/860/8b0014b...apasel422:bf3a1bc.html" title="Last updated on Jun 22, 2023, 6:06 PM UTC (bf3a1bc)">Diff</a>
=> Fix type error in "parse attribution destinations"

flexible_event_config.md
This change keeps the proposal backwards compatible with the current API.
=> Change the default of `max_event_level_reports` in the flexible explainer

index.bs
The current algorithm hedges and falls back to the last window if no windows match. This shouldn't be possible, so assert that.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/869.html" title="Last updated on Jun 26, 2023, 9:25 PM UTC (f3be61c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/869/0a5b869...f3be61c.html" title="Last updated on Jun 26, 2023, 9:25 PM UTC (f3be61c)">Diff</a>
=> Simplify "obtain an event-level report delivery time"

index.bs
Fixes #618 and unifies the handling of the general concept of a "report window" across event and aggregatable reports.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/870.html" title="Last updated on Jun 26, 2023, 11:31 PM UTC (2b91846)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/870/80decd8...2b91846.html" title="Last updated on Jun 26, 2023, 11:31 PM UTC (2b91846)">Diff</a>
=> Refactor aggregatable report windows

index.bs
For ease of linking and lookup.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/871.html" title="Last updated on Jun 27, 2023, 1:52 PM UTC (1fe0e52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/871/2f60ca5...apasel422:1fe0e52.html" title="Last updated on Jun 27, 2023, 1:52 PM UTC (1fe0e52)">Diff</a>
=> Extract constant for max destinations per source

EVENT.md
Reducing the event_report_window minimum from 86400 seconds (1 day) to 3600 seconds (1 hour)
=> Reducing event_report_window minimum

header-validator/data.source.js, header-validator/validate-json.js, index.bs, schema/source.schema.json
Fixes #561. Because this change only addresses the report windows and not the expiry, the privacy attack outlined in https://github.com/WICG/attribution-reporting-api/issues/561#issuecomment-1262347679 is not possible.
This PR also makes one behavior change: if durations are passed in with negative values, we error out rather than clamping.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/876.html" title="Last updated on Jun 29, 2023, 2:34 PM UTC (558b39b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/876/fe4f2a4...558b39b.html" title="Last updated on Jun 29, 2023, 2:34 PM UTC (558b39b)">Diff</a>
=> Set the min event-report-window to 1 hour

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/881.html" title="Last updated on Jul 6, 2023, 4:58 PM UTC (8e40595)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/881/5176031...apasel422:8e40595.html" title="Last updated on Jul 6, 2023, 4:58 PM UTC (8e40595)">Diff</a>
=> Add caveat about event-level trigger priority to reporting-delay-concern mitigations

flexible_event_config.md
We may explore implementing this logic using more general capabilities.
=> Remove `start_time` from flexible explainer

index.bs
This PR depends on https://github.com/WICG/attribution-reporting-api/pull/855. This PR specifies a partial version of https://github.com/WICG/attribution-reporting-api/blob/main/flexible_event_config.md, i.e. everything except the `trigger_specs` behavior.
In particular, this allows for a wider range of configurability in the event-level reports, in the form of:
- Allows specifying anywhere between 1 and 5 reporting windows, with (mostly) arbitrary times
- Allows specifying anywhere between 1 and 20 total reports
Fixes #736
Fixes #730 
Addresses #849 % channel capacity limits
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/856.html" title="Last updated on Jul 17, 2023, 4:10 PM UTC (51dbcd8)">Preview</a> | <a …
=> Add configurable windows and maximum # of reports to spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/893.html" title="Last updated on Jul 18, 2023, 12:54 PM UTC (e1f8bd1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/893/e3c2036...apasel422:e1f8bd1.html" title="Last updated on Jul 18, 2023, 12:54 PM UTC (e1f8bd1)">Diff</a>
=> Fix use-before-def in "parse report windows" algorithm

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/894.html" title="Last updated on Jul 18, 2023, 1:09 PM UTC (eef5e9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/894/e3c2036...apasel422:eef5e9e.html" title="Last updated on Jul 18, 2023, 1:09 PM UTC (eef5e9e)">Diff</a>
=> Require end_times durations to be positive

index.bs
Their values are constrained to the ranges [86400, 2592000] and [3600, 2592000], respectively, and the corresponding fields in #856 are integers, not strings.
Part of #888.
We will update the header validator and JSON schema separately.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/895.html" title="Last updated on Jul 18, 2023, 2:29 PM UTC (fa6b44e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/895/412bdd6...apasel422:fa6b44e.html" title="Last updated on Jul 18, 2023, 2:29 PM UTC (fa6b44e)">Diff</a>
=> Allow source expiry and report_window durations to be integers

flexible-event/flexible_event_privacy.py
This PR adds some flavor to what a dynamic epsilon would look like if we did not unconditionally fail registrations exceeding the info bar in the flexible event config proposal.
=> Dynamic epsilon computation

flexible-event/main.ts, flexible-event/tsconfig.json
- Enable strict type-checking
- Exclude node modules from compilation
- Handle more instances of invalid source registration JSON
=> Clean up flexible-event package

index.bs
Fix https://github.com/WICG/attribution-reporting-api/issues/769
Support lookback window by adding an optional reserved keyword "_lookback_window" to trigger's filters.
When set, the field is parsed as a duration in seconds.
To decide if a filter matches, we first check the lookback window. If available, the duration since the source was registered must be smaller or equal to the lookback window duration.
**Backward incompatibility**:  By introducing a new reserved keyword, we break source registrations which are currently using the "_lookback_window" key.
***
<a href="https://pr-preview.s3.amazonaws.com/agarant/attribution-reporting-api/pull/914.html" title="Last updated on Aug 2, 2023, 5:43 PM UTC (da3c1bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-repo …
=> Specify lookback window

header-validator/src/validate-os.test.ts, header-validator/src/validate-os.ts
Now that these headers may contain lists of URLs, the index helps pinpoint the problem.
=> Include index of invalid item in OS-header-validation errors

header-validator/src/validate-eligible.ts, header-validator/src/validate-os.ts
This header supports only one optional parameter, so the abstractions were increasing complexity for no benefit.
=> Simplify OS-header validation and fix type issues

header-validator/src/source.data.test.ts, header-validator/src/validate-json.ts
Without this change, certain inputs crash the validator on `null`.
=> Fix erroneous treatment of JSON null as object

header-validator/src/source.data.test.ts, header-validator/src/validate-json.ts
Filter-data values are effectively a set, so there's no benefit to specifying the same one multiple times.
=> Warn about duplicate filter-data values

index.bs
- Introduce a map for trigger data cardinalities, akin to "Default event-level attributions per source"
- Move expiry rounding closer to where the value is first obtained
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/943.html" title="Last updated on Aug 10, 2023, 4:15 PM UTC (521352a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/943/53c270c...apasel422:521352a.html" title="Last updated on Aug 10, 2023, 4:15 PM UTC (521352a)">Diff</a>
=> Tidy source-type-specific registration parsing

header-validator/src/trigger.data.test.ts, header-validator/src/validate-json.ts
Per the spec, this field is effectively a set, so there is no benefit to specifying the same value multiple times.
=> Warn about duplicate source keys

header-validator/src/trigger.test.ts, header-validator/src/validate-json.ts
This is already supported in Chromium, but was omitted from the validator unintentionally. (Same problem as in #963.)
=> Allow or-filters in aggregatable dedup keys

EVENT.md, index.bs
Enhances #914 
At a high level, the currently spec logic is the following:
```
Negated filter true = (no lookback_window || outside lookback_window) || (has empty intersection for all matching keys)
```
This behavior is incoherent with other filtering logic, since as soon as a source is outside of the lookback window, the negated filter would match even if some matching keys have non-empty intersections. It also means that it can still match even if outside of the lookback window so long as it has empty intersection for all matching keys.
This PR updates the logic to the following:
```
Negated filter true = (no lookback_window || outside lookback_window)  &&  (has empty intersection for all matching keys)
```
This is more coherent and being able to match when outside of the lookback …
=> Lookback window within negated filter

index.bs
It is complex enough to merit this.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/962.html" title="Last updated on Aug 28, 2023, 1:34 PM UTC (7ef74c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/962/e9ee6d3...apasel422:7ef74c8.html" title="Last updated on Aug 28, 2023, 1:34 PM UTC (7ef74c8)">Diff</a>
=> Split event-level report-prioritization into its own algorithm

header-validator/src/index.ts, header-validator/src/source.test.ts, header-validator/src/trigger.test.ts, header-validator/src/validate-json.test.ts, header-validator/src/validate-json.ts
Per the spec, the value is not fixed at 20:
https://wicg.github.io/attribution-reporting-api/#max-aggregation-keys-per-attribution
=> Move aggregation-key limit to vendor-specific values

EVENT.md, flexible_event_config.md, index.bs
This delay doesn't provide a significant reduction in the ability of the reporting origin to join the report with the attribution via other mechanisms. Removing it makes the report-time algorithm easier to understand and may reduce transmission errors.
=> Remove 1-hour delay between end of report window and transmission

header-validator/src/maybe.ts, header-validator/src/source.test.ts, header-validator/src/validate-json.ts
- aggregatable_report_window is clamped to (1 hour, expiry)
- event_report_window is clamped to (1 hour, expiry)
- event_report_windows.start_time must be <= expiry
- event_report_window.end_times is clamped to (1 hour, expiry)
- event_report_windows.end_times[0] must be > start_time
- event_report_windows.end_times must be strictly increasing
=> Fully validate report window(s) with respect to expiry

header-validator/src/validate-json.ts
Rename boolean returning functions to make them more distinctive from the functions returning parsed values.
=> Rename boolean returning functions

header-validator/index.html, header-validator/src/index.ts, header-validator/src/source.test.ts, header-validator/src/trigger.test.ts, header-validator/src/validate-json.test.ts, header-validator/src/validate-json.ts
This is necessary to ensure that expiry and the fields that depend on it (event_report_window, event_report_windows, aggregatable_report_window) are fully validated.
We present a new radio button in the UI to allow the user to choose which type to validate against.
=> Validate source registrations using a specific source type

index.bs
By removing only elements that were greater than eventReportWindow, this algorithm would have erroneously placed duplicate values in the deadlines list if the eventReportWindow was exactly 2 days or 7 days. In turn, this would have caused the returned windows list to contain 1 extra window.
This seems to have been an oversight in #742.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/992.html" title="Last updated on Sep 6, 2023, 1:05 PM UTC (fa35d8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/992/2b4773a...apasel422:fa35d8c.html" title="Last updated on Sep 6, 2023, 1:05 PM UTC (fa35d8c)">Diff</a>
=> Prevent duplicate values in "obtain default effective windows" algorithm

header-validator/src/index.ts, header-validator/src/validate-json.ts
Now that the validator is source-type-aware, this will allow us to show the effective value in the UI and use it for channel-capacity computations.
=> Default max_event_level_reports in header validator

ts/src/flexible-event/privacy.test.ts, ts/src/flexible-event/privacy.ts
This was an oversight in #1010.
=> Remove redundant SourceType enum

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
Since there may be more than one.
=> Rename Source.eventReportWindow to eventReportWindows

ts/src/header-validator/index.ts, ts/src/header-validator/validate-json.test.ts, ts/src/header-validator/validate-json.ts, ts/src/vendor-specific-values.ts
For reuse in the flexible-event directory.
=> Move vendor-specific values to separate file

Makefile, ts/package.json
This helps prevent redundant build operations, which can be slow.
=> Separate build/pack Node scripts

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts, ts/src/vendor-specific-values.ts
If vendor-specific values are enabled and the source is otherwise valid, an error will be omitted if the effective channel capacity of the source is greater than the limit for the selected source type.
=> Check event-level channel capacity limit in header validator

index.bs, params/chromium-params.md, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts, ts/src/vendor-specific-values.ts
This limit is non-privacy related, therefore we can just rely on the limit on total header size.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/988.html" title="Last updated on Sep 15, 2023, 8:14 PM UTC (3c3f927)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/988/35aa3dc...linnan-github:3c3f927.html" title="Last updated on Sep 15, 2023, 8:14 PM UTC (3c3f927)">Diff</a>
=> Remove aggregation keys size limit on trigger registration

EVENT.md
=> Document that the `fetch` API needs to allow `credentials` to set the debug cookie

index.bs, params/chromium-params.md, ts/src/constants.ts, ts/src/flexible-event/main.ts, ts/src/flexible-event/privacy.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts, ts/src/vendor-specific-values.ts
Now that max_event_level_reports is configurable per source registration and that implementations can impose constraints via https://wicg.github.io/attribution-reporting-api/#max-event-level-channel-capacity-per-source, there seems to be little benefit for different implementations to have different defaults here. Making this a constant ensures interoperability between specs, simplifies logic for reporting origins and implementers, and eliminates the only remaining source-parsing behavior that the spec allows to vary in this way.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1022.html" title="Last updated on Sep 19, 2023, 6:43 PM UTC (ebacff1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1022/ec0778c. …
=> Make default event-level attributions per source a spec constant

ts/src/header-validator/validate-json.test.ts
Previously, the value check was performed outside the scope of the test() call in util.test.ts, making failure output misleading.
=> Check expected values within subtest

index.bs
Resolves #352.
See also the related spec change for the Private Aggregation API: https://github.com/patcg-individual-drafts/private-aggregation-api/pull/98. See also the corresponding ARA explainer change: #1031.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1030.html" title="Last updated on Sep 26, 2023, 9:20 PM UTC (11f2e08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1030/ec0778c...11f2e08.html" title="Last updated on Sep 26, 2023, 9:20 PM UTC (11f2e08)">Diff</a>
=> Spec: Pad the payload with null contributions

ts/src/header-validator/index.html, ts/src/header-validator/index.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
Proper validation relies more and more on the presence of all
vendor-specific values, so requiring this here simplifies the code,
especially for the forthcoming Full Flexible Event-Level changes.
If there are alternative vendor-specific values in the future, we will
expose them in the interactive header validator using a dropdown menu.
=> Require vendor-specific values for source/trigger validation

ts/src/constants.ts, ts/src/flexible-event/main.ts, ts/src/flexible-event/privacy.test.ts, ts/src/flexible-event/privacy.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.test.ts, ts/src/header-validator/validate-json.ts
This replaces the ad-hoc parsing and validation in the Flexible Event privacy scripts.
By default, parsing of these fields is disabled in the interactive header validator, since they are unspecified and subject to change.
=> Add speculative parsing for Full Flexible Event-Level source registrations

flexible_event_config.md, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
This allows us to retain backwards compatibility with the existing modulus behavior while allowing sources to opt in to exact matching. Other matching modes, such as `clamp_min`, `clamp_max`, and `clamp`, could be added in the future.
Fixes #765
=> Add trigger_data_matching field to Flexible Event explainer

index.bs, params/chromium-params.md, ts/src/constants.ts, ts/src/header-validator/validate-json.ts
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1065.html" title="Last updated on Oct 10, 2023, 2:34 PM UTC (612c67b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1065/7b8dc41...612c67b.html" title="Last updated on Oct 10, 2023, 2:34 PM UTC (612c67b)">Diff</a>
=> `Allowed aggregatable budget per source` should be a constant

index.bs
It feels a bit circular to define it in terms of the last value of the default windows, when the default windows are only used when the `event_report_windows` field is absent.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1057.html" title="Last updated on Oct 2, 2023, 7:48 PM UTC (e29316e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1057/e1dc946...apasel422:e29316e.html" title="Last updated on Oct 2, 2023, 7:48 PM UTC (e29316e)">Diff</a>
=> Express "parse report windows" algorithm in terms of expiry

index.bs
Discussed with @domfarolino, top-level traversal is the right way to get top-level document.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1070.html" title="Last updated on Oct 12, 2023, 5:36 PM UTC (aa8c265)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1070/6198a8c...linnan-github:aa8c265.html" title="Last updated on Oct 12, 2023, 5:36 PM UTC (aa8c265)">Diff</a>
=> Fix context origin definition in spec

index.bs
Fenced frame monkeypatches was moved to fenced frame spec: https://github.com/WICG/fenced-frame/pull/127
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1072.html" title="Last updated on Oct 12, 2023, 6:19 PM UTC (890acbe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1072/e398988...linnan-github:890acbe.html" title="Last updated on Oct 12, 2023, 6:19 PM UTC (890acbe)">Diff</a>
=> Remove fenced frame monkeypatches

AGGREGATE.md, index.bs
Add version to the .well-known path, this allows future changes to public keys. This changes the endpoint for the client (e.g Chrome) to fetch public keys, and the ad-techs are not impacted.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1053.html" title="Last updated on Oct 16, 2023, 4:17 PM UTC (95377ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1053/74450a3...linnan-github:95377ba.html" title="Last updated on Oct 16, 2023, 4:17 PM UTC (95377ba)">Diff</a>
=> Add version to the aggregation coordinator public key endpoint

index.bs
See https://chromium-review.googlesource.com/c/chromium/src/+/4909556 for the chromium change.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1060.html" title="Last updated on Oct 4, 2023, 2:43 PM UTC (c8a7a00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1060/90b576c...c8a7a00.html" title="Last updated on Oct 4, 2023, 2:43 PM UTC (c8a7a00)">Diff</a>
=> Make it clear the channel capacity of the unary channel is 0

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1077.html" title="Last updated on Oct 18, 2023, 1:43 PM UTC (6d81385)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1077/c96f1fe...apasel422:6d81385.html" title="Last updated on Oct 18, 2023, 1:43 PM UTC (6d81385)">Diff</a>
=> Fix variable-reference typo in "parse report windows"

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1073.html" title="Last updated on Oct 16, 2023, 1:20 PM UTC (77ebc5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1073/11882e6...linnan-github:77ebc5b.html" title="Last updated on Oct 16, 2023, 1:20 PM UTC (77ebc5b)">Diff</a>
=> attributionsrc eligible response handling should handle in parallel

index.bs
Followup to #1044
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1064.html" title="Last updated on Oct 12, 2023, 6:05 PM UTC (deb2bf0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1064/7b8dc41...apasel422:deb2bf0.html" title="Last updated on Oct 12, 2023, 6:05 PM UTC (deb2bf0)">Diff</a>
=> Specify trigger-data matching

index.bs, ts/src/constants.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1066.html" title="Last updated on Oct 16, 2023, 1:47 PM UTC (d4c010c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1066/6198a8c...linnan-github:d4c010c.html" title="Last updated on Oct 16, 2023, 1:47 PM UTC (d4c010c)">Diff</a>
=> Specify max bytes per filter string and max bytes per aggregation key identifier as constants

AGGREGATE.md
The existing key id is actually longer than the limit and will fail.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/484.html" title="Last updated on Nov 30, 2022, 8:59 PM UTC (d2d1a80)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/484/8020de4...d2d1a80.html" title="Last updated on Nov 30, 2022, 8:59 PM UTC (d2d1a80)">Diff</a>
=> Shorten aggregation key id example

index.bs, params/chromium-params.md, ts/src/constants.ts, ts/src/flexible-event/privacy.test.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts, ts/src/vendor-specific-values.ts
Similar to #1022 and the preexisting [default event-level report windows](https://wicg.github.io/attribution-reporting-api/#obtain-default-effective-windows), there is significant benefit in making these constants instead of vendor-specific values:
1. Users of the API can reliably depend on them without having to either maintain a map of them per user agent or interpret a browser-advertised configuration (e.g. a request header, which does not exist today.) Users of the API that are today assuming only Chromium's specific values without using one of those approaches are subject to unintended behavior with other implementations.
2. Implementations of the API can be simplified knowing that these values are fixed, making it easier, e.g., to maintain an interoperability-test runner.
***
<a …
=> Make default trigger data cardinality a constant

index.bs
Instead of using the default trigger data cardinality directly, it is defined in terms of a map of allowed trigger data values and their corresponding number of report windows.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1078.html" title="Last updated on Oct 20, 2023, 3:06 PM UTC (d396291)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1078/71c9752...apasel422:d396291.html" title="Last updated on Oct 20, 2023, 3:06 PM UTC (d396291)">Diff</a>
=> Abstract randomized response output configuration

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1080.html" title="Last updated on Oct 20, 2023, 5:48 PM UTC (2dc5961)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1080/b90aab0...apasel422:2dc5961.html" title="Last updated on Oct 20, 2023, 5:48 PM UTC (2dc5961)">Diff</a>
=> Fix erroneous field reference

index.bs
This will make it easier to reuse for Full Flex.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1082.html" title="Last updated on Oct 23, 2023, 4:12 PM UTC (7588144)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1082/2f80c94...apasel422:7588144.html" title="Last updated on Oct 23, 2023, 4:12 PM UTC (7588144)">Diff</a>
=> Move total-report window algorithm from source to report window list

index.bs
Note that we do not *use* the corresponding algorithms yet.
We will handle the `summary_window_operator` and `summary_buckets` fields separately.
https://github.com/WICG/attribution-reporting-api/blob/main/flexible_event_config.md#phase-2-full-flexible-event-level
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1074.html" title="Last updated on Oct 23, 2023, 3:58 PM UTC (0660908)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1074/2f80c94...apasel422:0660908.html" title="Last updated on Oct 23, 2023, 3:58 PM UTC (0660908)">Diff</a>
=> Specify parsing of trigger_specs' trigger_data and event_report_windows

EVENT.md, index.bs
This is more privacy-preserving, and aligns with attribution-success debug reports.
Also updated the cookie-based debugging algorithm to check whether cookie access is allowed for the reporting site on the context site. This check is necessary besides the explicit check for the special debug cookie to ensure that the reporting site can actually access the debug cookie on the context site.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1088.html" title="Last updated on Oct 30, 2023, 1:41 PM UTC (265c0af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1088/35a730e...linnan-github:265c0af.html" title="Last updated on Oct 30, 2023, 1:41 PM UTC (265c0af)">Diff</a>
=> Require ar_debug cookie presence on source registrations for trigger verbose debug reports

index.bs, ts/src/constants.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts, ts/src/vendor-specific-values.ts
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1096.html" title="Last updated on Nov 7, 2023, 3:30 PM UTC (647099d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1096/c47f837...linnan-github:647099d.html" title="Last updated on Nov 7, 2023, 3:30 PM UTC (647099d)">Diff</a>
=> Make max aggregation keys per source constant

index.bs
Otherwise, if the report time is adjusted, either due to retries or the browser being offline, the wrong report time will be used, which can cause later reports to erroneously replace earlier ones that haven't been successfully sent yet.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1098.html" title="Last updated on Nov 8, 2023, 1:37 PM UTC (8ccdb52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1098/5fd28d6...apasel422:8ccdb52.html" title="Last updated on Nov 8, 2023, 1:37 PM UTC (8ccdb52)">Diff</a>
=> Scope event-level report prioritization using original report time

index.bs
This also fixes an inconsistency in which the fake report's report time was overridden but not its original report time, and matches [what Chromium's implementation is already doing](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/attribution_reporting/attribution_storage_sql.cc;l=685;drc=7fa0c25da15ae39bbd2fd720832ec4df4fee705a).
Fixes #727
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1099.html" title="Last updated on Nov 9, 2023, 4:28 PM UTC (9bd36ad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1099/9259427...apasel422:9bd36ad.html" title="Last updated on Nov 9, 2023, 4:28 PM UTC (9bd36ad)">Diff</a>
=> Use realistic trigger time for fake reports

index.bs
The list is sorted two steps below.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1104.html" title="Last updated on Nov 9, 2023, 7:39 PM UTC (ee22a43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1104/b0aa8a3...apasel422:ee22a43.html" title="Last updated on Nov 9, 2023, 7:39 PM UTC (ee22a43)">Diff</a>
=> Remove redundant sorting step from "maybe replace event-level report"

params/chromium-params.md
From UMA metrics, we identified that a higher than expected number of sources were being dropped due to the limit of 1024 sources per source origin, specifically ~6% are being dropped due to it.
This was also reported in https://github.com/WICG/attribution-reporting-api/issues/1103
A first step toward mitigating this issue is to increase the limit from 1024 to 4096. Analyses were conducted to confirm that no problematic increase in storage usage is expected from this change.
=> Increase max pending sources per source origin

index.bs
Event-level report deduplication is based only on whether a given deduplication key has previously been seen for a given source. As such, it makes more sense to perform deduplication as soon as both of these values are known, instead of after the event-report-window check, which is not special with respect to any of the existing checks that are already performed after deduplication.
This change affects backwards compatibility in a minor way, in that the "trigger-event-deduplicated" verbose debug report will now be sent preferentially over the "trigger-event-report-window-not-started" and "trigger-event-report-window-passed" verbose debug reports, but this only affects triggers that are allowed to send verbose debug reports at all and is only observable when both such failure conditions …
=> Perform event-report-window check after deduplication instead of before

index.bs
The algorithm may run in parallel: https://wicg.github.io/attribution-reporting-api/#maybe-defer-and-then-complete-trigger-attribution
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1108.html" title="Last updated on Nov 13, 2023, 2:15 PM UTC (6b6551e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1108/23dca6b...linnan-github:6b6551e.html" title="Last updated on Nov 13, 2023, 2:15 PM UTC (6b6551e)">Diff</a>
=> Queue a task to trigger attribution

index.bs
We remove reports from the cache prior to sending them to ensure that reports that are truly pending (and therefore subject to modification or deletion for various reasons) are not mistaken for ones that are in the process of being sent. This also allows us to remove the separate fields for original report time and report time, as while a report is in the report cache, its report time is never modified.
Fixes #1101.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1105.html" title="Last updated on Nov 15, 2023, 3:00 PM UTC (cb26732)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1105/8b14390...apasel422:cb26732.html" title="Last updated on Nov 15, 2023, 3:00 PM UTC (cb26732)">Diff</a>
=> Reorganize report-delivery algorithms to prevent certain race conditions

ts/src/flexible-event/privacy.test.ts, ts/src/flexible-event/privacy.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
The warning part is related to #907.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1115.html" title="Last updated on Nov 21, 2023, 3:53 PM UTC (f53e28e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1115/ed340d6...apasel422:f53e28e.html" title="Last updated on Nov 21, 2023, 3:53 PM UTC (f53e28e)">Diff</a>
=> Fix unary-channel calculations and warn about inconsistent registrations

index.bs, ts/src/constants.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
Fixes #974 
Explainer: https://github.com/WICG/attribution-reporting-api/pull/1113
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1114.html" title="Last updated on Nov 21, 2023, 1:49 PM UTC (909ebee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1114/ed340d6...linnan-github:909ebee.html" title="Last updated on Nov 21, 2023, 1:49 PM UTC (909ebee)">Diff</a>
=> Spec supporting trigger context ID for aggregate reporting

flexible_event_config.md, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
The max_event_level_reports value (whether explicit or defaulted based on source type) restricts the maximum number of reports that can be produced from a single source. Therefore, it is misleading to have more than that number of summary_buckets, since bucket increments will stop once reaching max_event_level_reports.
Rejecting sources with inconsistent values in these fields will help prevent developer errors, and both the rejection and defaulting based on max_event_level_reports bounds the storage space needed per trigger_spec for the summary_buckets field to 20, which is the max settable value for max_event_level_reports.
This is a revival of #1021, which has more discussion.
=> Default and limit summary_buckets based on max_event_level_reports

index.bs
Includes the definition for summary window operator and summary bucket structure.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1111.html" title="Last updated on Dec 1, 2023, 9:36 PM UTC (7406c72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1111/b0aa8a3...7406c72.html" title="Last updated on Dec 1, 2023, 9:36 PM UTC (7406c72)">Diff</a>
=> Summary buckets and window operator parsing algorithm

EVENT.md
Add explanation about debugging for specific use cases. b/314977849
Adds note that browsers may choose to enable debugging for specific use-cases (for example, reporting origins can enable debugging without the cookie check for [Mode B groups during Chrome-facilitated testing](https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/#mode-b)).
=> Update Attribution Reporting EVENT.md to note that browsers may choose to enable debugging for specific use-cases

flexible_event_config.md
Otherwise, their behavior varies based on whether the source is event or navigation and/or causes a parse error per #1116 due to the size of `summary_buckets` exceeding `max_event_level_reports`.
=> Set max_event_level_reports in Flex examples

AGGREGATION_SERVICE_TEE.md
This PR updates how the epsilon value of Aggregation Service will be handled during the third-party cookie deprecation.
=> Update Aggregation Service's epsilon range info

EVENT.md
Per the spec, source_event_id is parsed as a 64-bit unsigned integer and never adjusted.
=> Remove inaccurate mention of modulus on source_event_id field

index.bs
Many fields in the trigger is irrelevant of event-level report generation. Removed fakeTrigger and passed the corresponding fields into the algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1135.html" title="Last updated on Jan 4, 2024, 7:07 PM UTC (936a053)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1135/be4d34b...linnan-github:936a053.html" title="Last updated on Jan 4, 2024, 7:07 PM UTC (936a053)">Diff</a>
=> Clean up fake report generation

index.bs
Now that source fields other than filter data affect matching (i.e. lookback window), the new names are more applicable in addition to being less verbose.
This also fixes an apparent issue with Bikeshed and curly quotes in algorithm names that was preventing the spec from building (e.g. #1152).
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1153.html" title="Last updated on Jan 31, 2024, 2:20 PM UTC (5d60e95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1153/422b076...apasel422:5d60e95.html" title="Last updated on Jan 31, 2024, 2:20 PM UTC (5d60e95)">Diff</a>
=> Simplify filter-matching algorithm names

ts/src/flexible-event/main.ts, ts/src/header-validator/context.ts, ts/src/header-validator/index.html, ts/src/header-validator/index.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/util.test.ts, ts/src/header-validator/validate-json.ts
We also change the command-line output to resemble that of the event-level reports by using `randomized trigger rate` instead of `flip probability` and decimals instead of percentages.
=> Show information gain in header validator output

EVENT.md, flexible_event_config.md, index.bs, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
This implements a subset of the Full Flexible Event proposal, allowing custom trigger data (both values and cardinality) via a new top-level `"trigger_data": [...]` field and the Full Flex proposal's `"trigger_data_matching": "exact"`.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 2, 2024, 5:14 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fapasel422%2Fattribution-reporting-api%2Fca946c4be03d8 …
=> Allow sources to customize trigger data cardinality and values

AGGREGATE.md, index.bs, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
This allows for a list of dictionaries to be taken in for the `aggregatable_values` field in trigger registrations, where each dictionary contains a dictionary of aggregatable values as well as a pair of filters, allowing for filtering aggregation keys on the trigger side. This change is backwards compatible and maintains original behavior as well.
Resolves #649.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1149.html" title="Last updated on Feb 12, 2024, 4:34 PM UTC (f1ff596)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1149/5ec6061...f1ff596.html" title="Last updated on Feb 12, 2024, 4:34 PM UTC (f1ff596)">Diff</a>
=> Allow trigger side filtering on aggregation keys

index.bs
We only report the first encountered error in the attribution registration.
To better mitigate security concerns on the global destination limit, moving the check later so that whether the limit is actually hit cannot be inferred from the presence of other explicitly reported errors.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1170.html" title="Last updated on Feb 21, 2024, 7:39 PM UTC (1e93546)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1170/7481d1e...linnan-github:1e93546.html" title="Last updated on Feb 21, 2024, 7:39 PM UTC (1e93546)">Diff</a>
=> Move time-based destination limit check later

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1175.html" title="Last updated on Feb 27, 2024, 6:44 PM UTC (150d109)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1175/84e1696...linnan-github:150d109.html" title="Last updated on Feb 27, 2024, 6:44 PM UTC (150d109)">Diff</a>
=> Use spec8941 for structured headers

index.bs
This is to align with the Chromium implementation such that the nullness check of the OS registration only checks the presence of the header but not the validity.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1177.html" title="Last updated on Feb 27, 2024, 9:11 PM UTC (f25519c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1177/c574fa5...linnan-github:f25519c.html" title="Last updated on Feb 27, 2024, 9:11 PM UTC (f25519c)">Diff</a>
=> Fix OS registration header nullness checking

index.bs
This matches what the Chromium implementation is already doing.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1171.html" title="Last updated on Feb 22, 2024, 3:32 PM UTC (bfe19ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1171/7481d1e...apasel422:bfe19ff.html" title="Last updated on Feb 22, 2024, 3:32 PM UTC (bfe19ff)">Diff</a>
=> Specify randomized_trigger_rate rounding in report bodies

ts/src/header-validator/validate-os.test.ts, ts/src/header-validator/validate-os.ts
[The spec](https://wicg.github.io/attribution-reporting-api/#get-os-registrations-from-a-header-value) and [the implementation](https://source.chromium.org/chromium/chromium/src/+/main:components/attribution_reporting/os_registration.cc;l=47?q=os_registration.cc&ss=chromium%2Fchromium%2Fsrc) are ignoring invalid urls but still consider the header to be valid. 
This PR updates the header validator to issue warnings instead of errors when encountering invalid urls.
=> OS registration header validator - replace invalid urls errors with warnings

EVENT.md, verbose_debugging_reports.md
Strictly, an eTLD+1 is just a host, whereas for Attribution Reporting matching is always performed using a host + scheme, i.e. a site.
=> Replace eTLD+1 with site in explainers

index.bs, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1192.html" title="Last updated on Mar 13, 2024, 1:07 PM UTC (2efb71d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1192/de3175e...apasel422:2efb71d.html" title="Last updated on Mar 13, 2024, 1:07 PM UTC (2efb71d)">Diff</a>
=> Specify parsing of Full Flex event_trigger_data value

ts/src/header-validator/validate-os.test.ts, ts/src/header-validator/validate-os.ts
[The spec](https://wicg.github.io/attribution-reporting-api/#get-os-registrations-from-a-header-value) and [the implementation](https://source.chromium.org/chromium/chromium/src/+/main:components/attribution_reporting/os_registration.cc;l=47?q=os_registration.cc&ss=chromium%2Fchromium%2Fsrc) are not checking that the URL is potentially trustworthy.
This PR aligns the validator with it.
=> Remove potentially trustworthy URL warning from validator

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1200.html" title="Last updated on Mar 19, 2024, 6:00 PM UTC (5a5ee33)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1200/e4b0497...apasel422:5a5ee33.html" title="Last updated on Mar 19, 2024, 6:00 PM UTC (5a5ee33)">Diff</a>
=> Fix broken spec references

index.bs
This is to fix the algorithm which should return the set.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1206.html" title="Last updated on Mar 20, 2024, 3:24 PM UTC (48146a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1206/8501298...linnan-github:48146a3.html" title="Last updated on Mar 20, 2024, 3:24 PM UTC (48146a3)">Diff</a>
=> Return value for obtaining possible trigger states algorithm

ts/src/header-validator/validate-eligible.test.ts, ts/src/header-validator/validate-eligible.ts
After #757, user code no longer manually sets the
Attribution-Reporting-Eligible header, but the validator was never updated to properly reflect that.
We remove the warning about navigation-source (since the header is effectively always browser-set) and add errors corresponding to [nonexistent key combinations](https://wicg.github.io/attribution-reporting-api/#set-attribution-reporting-headers) (navigation-source always occurs in isolation).
=> Adjust eligibility-header validation with respect to fetch options

index.bs
The privacy-neutral argument would depend on the order of the checks. To reduce complexity, gate all source verbose debug reports behind cookie access.
Note that this change is backwards incompatible as source-destination-limit and source-destination-rate-limit debug reports now require ar_debug cookie. There is no major concern as we expect that ad-techs that enable source verbose debug reports would already set ar_debug cookie.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1204.html" title="Last updated on Mar 19, 2024, 11:48 PM UTC (f9e10a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1204/8501298...linnan-github:f9e10a6.html" title="Last updated on Mar 19, 2024, 11:48 PM UTC …
=> Gate all source verbose debug reports behind cookie access

index.bs, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts, ts/src/vendor-specific-values.ts
Estimated channel capacity when the number of states is sufficiently high is effectively zero, and a randomised source response is effectively guaranteed. Additionally, a very high number of states coupled with the complexity of the flexible event feature can present challenges to performance. Altogether, user-agents may have cause to restrict the total number of report states per source.
***
<a href="https://pr-preview.s3.amazonaws.com/giladbarkan-github/attribution-reporting-api/pull/1203.html" title="Last updated on Mar 22, 2024, 12:57 PM UTC (dca4f8d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1203/d991bb9...giladbarkan-github:dca4f8d.html" title="Last updated on Mar 22, 2024, 12:57 PM UTC (dca4f8d)">Diff</a>
=> Restrict the number of report states per source

index.bs
fixes: https://github.com/WICG/attribution-reporting-api/issues/1202
- Prevent header coalescing when receiving the web registration headers.
- Reject the headers if more than 1 is received.
***
<a href="https://pr-preview.s3.amazonaws.com/agarant/attribution-reporting-api/pull/1212.html" title="Last updated on Mar 27, 2024, 3:39 PM UTC (30f5805)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1212/7e8b4c9...agarant:30f5805.html" title="Last updated on Mar 27, 2024, 3:39 PM UTC (30f5805)">Diff</a>
=> Prevent coalescing for web source/trigger headers

index.bs
New maps, sets, and lists, as indicated by their usage in the Infra spec, are implicitly empty, so calling them out as empty is unnecessary and also creates confusion in instances where they are not called out as empty.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1218.html" title="Last updated on Mar 27, 2024, 7:17 PM UTC (a0782af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1218/755d6a0...apasel422:a0782af.html" title="Last updated on Mar 27, 2024, 7:17 PM UTC (a0782af)">Diff</a>
=> Simplify spec language for new collections

index.bs
Add non-normative note about the security implications with the check order.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1220.html" title="Last updated on Mar 29, 2024, 12:47 PM UTC (b6647ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1220/c0e269d...linnan-github:b6647ef.html" title="Last updated on Mar 29, 2024, 12:47 PM UTC (b6647ef)">Diff</a>
=> Add note to spec about check orders in source registration for security concerns

AGGREGATE.md
The max aggregatable value should be L1 = 2^16.
=> Fix max aggregatable value typo in explainer

index.bs, verbose_debugging_reports.md
The "Max source reporting origins per source reporting site" limit is per reporting site, therefore it's less concerned from security perspective. We already report other rate-limits scoped by reporting site explicitly.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1225.html" title="Last updated on Apr 1, 2024, 12:59 PM UTC (8c43712)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1225/dd5e0e3...linnan-github:8c43712.html" title="Last updated on Apr 1, 2024, 12:59 PM UTC (8c43712)">Diff</a>
=> Report source reporting origins per site limit explicitly

index.bs
This improves the readability for attribution rate limits algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1232.html" title="Last updated on Apr 2, 2024, 4:32 PM UTC (8972e5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1232/3c4588d...linnan-github:8972e5e.html" title="Last updated on Apr 2, 2024, 4:32 PM UTC (8972e5e)">Diff</a>
=> Group attribution rate limits under one header

index.bs
This makes it easier to find all references to them.
We will do the same for triggers in a followup PR.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1236.html" title="Last updated on Apr 3, 2024, 2:39 PM UTC (bf9e7a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1236/2ba156f...apasel422:bf9e7a5.html" title="Last updated on Apr 3, 2024, 2:39 PM UTC (bf9e7a5)">Diff</a>
=> Add list of source-registration JSON keys

index.bs
To better mitigate security concerns with security concerning checks, e.g. max source reporting origins per rate-limit window and max destinations per reporting window, the debug data sent in the report should not change depend on the result of those checks.
This PR fixes the issue with sources with randomized response, and `source-noised` may be sent if those security concerning checks fail.
=> Determine debug data regardless of security concerning checks

EVENT.md, flexible_event_config.md, index.bs, verbose_debugging_reports.md
Currently, we have a single rate-limit which counts the overall attribution (either event or aggregate or both) of the trigger. This change separates the attribution counts for event & aggregate for accurate counting of reported conversions. This will facilitate easier report deletions counting as well as accurate counting for [Full Flex proposal](https://github.com/WICG/attribution-reporting-api/blob/main/flexible_event_config.md) where more than 1 event report may be generated per trigger.
1. Let's say there is 1 source (event) which is registered at t = 0: S
1. Trigger T1 registered at T = 1 and generates an event report E1 (priority=1) and no aggregatable reports
1. Trigger T2 registered at T = 2 and generates an event report E2 (priority=2) and no aggregatable reports. E2 will …
=> Split attribution rate-limit into separate event & aggregate rate-limits

index.bs, verbose_debugging_reports.md
Move computation of channel capacity out of parsing algorithm for explicit verbose debug reporting.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1223.html" title="Last updated on Apr 6, 2024, 1:14 AM UTC (2ada507)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1223/642d10c...linnan-github:2ada507.html" title="Last updated on Apr 6, 2024, 1:14 AM UTC (2ada507)">Diff</a>
=> Spec verbose debug report for max channel capacity and max trigger states cardinality

index.bs
Also added trigger verification metadata to the signature of processing attributionsrc eligible response.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1238.html" title="Last updated on Apr 9, 2024, 5:15 PM UTC (dedb770)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1238/932c677...linnan-github:dedb770.html" title="Last updated on Apr 9, 2024, 5:15 PM UTC (dedb770)">Diff</a>
=> Update spec to not sending debug reports for fenced frames

Makefile
The existing wildcard didn't properly account for files in nested directories.
=> Add missing Makefile deps

ts/src/header-validator/index.ts, ts/src/header-validator/validate-os.test.ts, ts/src/header-validator/validate-os.ts
In a followup change, we will show the effective value of the header (i.e. with invalid values removed and defaults applied) in the interactive form.
=> Parse OS items in preparation for showing effective value

Makefile, ts/src/header-validator/filters-index.ts, ts/src/header-validator/filters.html, ts/src/header-validator/filters.test.ts, ts/src/header-validator/filters.ts, ts/src/header-validator/validate-json.ts, ts/webpack.config.js
This change adds an interactive form like the header validator to make it easier to experiment with this logic, which is non-trivial.
=> Add TypeScript implementation of filtering

index.bs
The correctness of our algorithms does not depend on these types being ordered, so it is clearer to omit the prefix.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1193.html" title="Last updated on May 3, 2024, 1:12 PM UTC (eed4291)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1193/1a9478a...apasel422:eed4291.html" title="Last updated on May 3, 2024, 1:12 PM UTC (eed4291)">Diff</a>
=> Remove irrelevant "ordered" prefix from map and set types

index.bs, ts/src/header-validator/event_level_report.test.ts, ts/src/header-validator/validate-json.ts
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1272.html" title="Last updated on May 7, 2024, 6:24 PM UTC (76b590f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1272/4d166c8...apasel422:76b590f.html" title="Last updated on May 7, 2024, 6:24 PM UTC (76b590f)">Diff</a>
=> Sort attribution destinations on parsing

index.bs
Fixes #1274.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1275.html" title="Last updated on May 7, 2024, 9:43 PM UTC (4882300)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1275/b635b93...apasel422:4882300.html" title="Last updated on May 7, 2024, 9:43 PM UTC (4882300)">Diff</a>
=> Make randomized source response a list instead of a set

index.bs
Without this, when an event-level report is being replaced, the limit ends up being `n - 1`.
Fixes #1267
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1268.html" title="Last updated on May 3, 2024, 5:58 PM UTC (4299151)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1268/1a9478a...apasel422:4299151.html" title="Last updated on May 3, 2024, 5:58 PM UTC (4299151)">Diff</a>
=> Skip event-level-reports-per-destination check for replaced reports

ara-tester-list.md
One line change to documentation to include Quantcast in the list of companies that are test the Attribution Reporting API
=> Update ara-tester-list.md to include Quantcast as a tester

ts/src/header-validator/aggregatable-contributions.test.ts, ts/src/header-validator/aggregatable-contributions.ts, ts/src/header-validator/validate-json.ts
Test cases are derived from
https://source.chromium.org/chromium/chromium/src/+/main:content/browser/attribution_reporting/aggregatable_attribution_utils_unittest.cc;drc=5ab0488632f969a12609bbbf09be18df61825e22
We will add an interactive form for experimenting with these in a followup change.
=> Add TypeScript implementation of aggregatable-histogram creation

index.bs
Moves the debug data generation to `triggering attribution` algorithm for simplification.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1285.html" title="Last updated on May 17, 2024, 6:14 PM UTC (4f5d359)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1285/4565ada...linnan-github:4f5d359.html" title="Last updated on May 17, 2024, 6:14 PM UTC (4f5d359)">Diff</a>
=> Refactor trigger verbose debug report generation in spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1293.html" title="Last updated on May 21, 2024, 1:39 PM UTC (b9bf97f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1293/758d2dc...apasel422:b9bf97f.html" title="Last updated on May 21, 2024, 1:39 PM UTC (b9bf97f)">Diff</a>
=> Remove erroneous early return

index.bs
Reverts WICG/attribution-reporting-api#1212 given issues discussed in https://github.com/WICG/attribution-reporting-api/issues/1202#issuecomment-2121954047.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1294.html" title="Last updated on May 21, 2024, 5:02 PM UTC (cb29b53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1294/9e8cf9f...cb29b53.html" title="Last updated on May 21, 2024, 5:02 PM UTC (cb29b53)">Diff</a>
=> Revert "Prevent coalescing for web source/trigger headers"

ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
It is no longer possible to know how trigger data will be modified, if at all, as it depends on the source's trigger_data_matching and trigger_data fields.
=> Remove warning about trigger-data sanitization

ts/src/header-validator/event_level_report.test.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
The regex are not validating the sizes of the integers. Renaming to make this clearer.
=> Rename integer regex

ts/src/header-validator/validate-json.ts
The struct validator already verifies that the type is object.
=> Remove redundant object check from event-level-report validator

ts/src/header-validator/validate-eligible.ts, ts/src/header-validator/validate-info.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-structured.ts, ts/src/header-validator/validate.ts
This allows the structured header validators to parse values into well-typed objects without ad-hoc logic.
`validate.ts` is effectively a module parameterized over a map type (`object` for JSON, `Map` for structured headers) and a value type (the `Json` type union for JSON, `Item | InnerList` for structured headers).
=> Share struct/field logic for JSON and structured headers

index.bs
This allows for more flexibility for other types of debug reporting.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1301.html" title="Last updated on May 24, 2024, 5:11 PM UTC (b2b0a80)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1301/c1d4157...linnan-github:b2b0a80.html" title="Last updated on May 24, 2024, 5:11 PM UTC (b2b0a80)">Diff</a>
=> Always return explicit debug data type for source registration errors and handle in verbose debug report processing

index.bs
The version should be explicit to match the aggregation service.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1305.html" title="Last updated on May 28, 2024, 4:16 PM UTC (946845d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1305/b2f438e...linnan-github:946845d.html" title="Last updated on May 28, 2024, 4:16 PM UTC (946845d)">Diff</a>
=> Set aggregatable report version explicitly

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1306.html" title="Last updated on May 28, 2024, 4:27 PM UTC (14b7d34)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1306/1dfec7d...linnan-github:14b7d34.html" title="Last updated on May 28, 2024, 4:27 PM UTC (14b7d34)">Diff</a>
=> Move note about report id to where it's set

attribution_scopes.md, params/chromium-params.md
Related to #1215 
Draft Explainer for Attribution Scopes Proposal.
This proposal also helps to address feedback from #1229
=> Attribution Scopes - New Explainer

aggregate_debug_reporting.md
=> Explainer for Aggregate Debug Reporting

index.bs, params/chromium-params.md
This is migrated from https://github.com/linnan-github/conversion-measurement-api/pull/2
Related to https://github.com/WICG/attribution-reporting-api/issues/705
Introduce aggregatable debug reports and rename aggregatable report to aggregatable attribution reports. Aggregatable report is the base class of aggregatable attribution report and aggregatable debug report.
Explainer: https://github.com/WICG/attribution-reporting-api/blob/main/aggregate_debug_reporting.md
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1310.html" title="Last updated on May 31, 2024, 6:17 PM UTC (4728fa9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1310/e7d7171...linnan-github:4728fa9.html" title="Last updated on May 31, …
=> Spec for aggregate debug reporting reports generation and delivery

ts/src/header-validator/event_level_report.test.ts, ts/src/header-validator/validate-json.ts
Since destinations are deduplicated during source registration, they can never appear in the report.
=> Prevent duplicates in event-level-report destination field

ts/src/header-validator/event_level_report.test.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
By round-tripping through the URL parser and serializer.
Without this, spurious issues are generated.
=> Compare suitable scopes case-insensitively

ts/src/header-validator/maybe.ts, ts/src/header-validator/validate-eligible.ts, ts/src/header-validator/validate-info.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-os.ts, ts/src/header-validator/validate-structured.ts, ts/src/header-validator/validate.ts
Combined with swapping the order of `CtxFunc`'s parameters, this allows a number of lambdas and lambda-captures to be eliminated.
=> Allow Maybe methods to invoke callbacks with additional arguments

index.bs
This is easier to check the order when new limits were added.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1325.html" title="Last updated on Jun 7, 2024, 1:25 PM UTC (290d16d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1325/f765a4a...linnan-github:290d16d.html" title="Last updated on Jun 7, 2024, 1:25 PM UTC (290d16d)">Diff</a>
=> Clarify source debug data types that are not reported implicitly for verbose debug reports

ts/src/header-validator/maybe.ts
Although any was safe due to the underlying field being readonly, never enables more precise type-checking, as such a value can never exist.
=> Use never instead of any with Maybe.None

ts/src/header-validator/maybe.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate.ts
It was unsound because it could be called with a Maybe<T> but its type parameter T instantiated with Maybe<T>, resulting in an apparent return type of Maybe<Maybe<T>>, but the instanceof check would cause the original Maybe<T> to be returned.
For example, the following code logs "number" despite y's type indicating that its value should be another Maybe:
```ts
const x = Maybe.some(5)
const y: Maybe<Maybe<number>> = Maybe.flatten<Maybe<number>>(x)
console.log(typeof y.value)
```
=> Remove Maybe.flatten function

EVENT.md, index.bs, params/chromium-params.md, ts/src/header-validator/source.test.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/validate-json.ts, verbose_debugging_reports.md
Fixes #1228 
To preserve the protection of user’s browser history, and also to mitigate utility concern with dropping new sources, we propose to change to FIFO+priority for the destination limit for unexpired sources. This change backwards incompatible.
We also propose a new limit on the max destinations per reporting site per day to mitigate the history reconstruction attack for FIFO.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1217.html" title="Last updated on Jun 10, 2024, 2:32 PM UTC (fd1758b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1217/221f474...linnan-github:fd1758b.html" title="Last updated on Jun 10, 2024, 2:32 PM UTC (fd1758b)">Diff</a>
=> Deactivate earliest destinations if exceeding distinct destination limit for unexpired sources

ts/src/header-validator/validate-eligible.ts, ts/src/header-validator/validate-info.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-os.ts, ts/src/header-validator/validate.ts
This allow us to merge the `field` and `fieldMaybeDefault` functions and makes it harder to accidentally make a field required (or optional).
=> Require explicit handling of optional and required fields

flexible_event_config.md
Per the subsequent examples, the bucket is reported as a tuple of the bucket start and end.
=> Remove obsolete description of summary-bucket-as-index

index.bs
Source-processing is already extremely complicated, and moving it to a separate algorithm will enable simpler refactoring in #1348.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1349.html" title="Last updated on Jun 26, 2024, 1:31 PM UTC (787c0ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1349/ae7d42b...apasel422:787c0ff.html" title="Last updated on Jun 26, 2024, 1:31 PM UTC (787c0ff)">Diff</a>
=> Move source-expiry to its own algorithm

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1351.html" title="Last updated on Jul 1, 2024, 5:37 PM UTC (f40ddfd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1351/bacfb84...linnan-github:f40ddfd.html" title="Last updated on Jul 1, 2024, 5:37 PM UTC (f40ddfd)">Diff</a>
=> Add non-normative note for event-level reports deletion for unexpired destination limit

flexible_event_config.md, index.bs, ts/src/header-validator/source.test.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/validate-json.ts
Fixes #1343
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1346.html" title="Last updated on Jun 24, 2024, 6:04 PM UTC (190d031)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1346/ae7d42b...apasel422:190d031.html" title="Last updated on Jun 24, 2024, 6:04 PM UTC (190d031)">Diff</a>
=> Rename summary window operator to summary operator

index.bs
Resolves issue https://github.com/WICG/attribution-reporting-api/issues/1309
In step 15 of https://wicg.github.io/attribution-reporting-api/#trigger-event-level-attribution, we exit early if the number of persisted attribution rate limit records is equal to the max allowed; which means we reach step 17, replacing event-level reports, only if the number of persisted attribution rate limit records is less than the max allowed, even though we keep the number of attribution rate limit records in line with the number of reports by removing attribution rate limit records (step 12 of https://wicg.github.io/attribution-reporting-api/#maybe-replace-event-level-report).
Since having (max-1) persisted attribution rate limit records results in report replacements unlimited by max attributions per …
=> Allow max attribution rate limit when replacing an event report

attribution_scopes.md
There is no size limit on trigger registrations.
=> Fix attribution_scopes explainer for size limits on triggers

index.bs, ts/src/constants.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
The current attribution logic in the Attribution Reporting API may not be ideal for use-cases where an ad-tech needs more fine grain control over the attribution granularity (i.e. campaign, product, conversion ID, etc.) before a source is chosen for attribution. Currently available features such as top-level filters are not fully sufficient for this use-case because they happen after a source has been selected (i.e. after attribution). We can optionally support this use-case by allowing callers of the API to specify predefined attribution scopes that will be considered for filtering before attributing a source, in order to more efficiently extract utility out of the API.
This PR covers the parsing logic for the new API surface.
***
<a …
=> Parsing changes for Pre-Attribution Filtering: Attribution Scope

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-json.ts
- Split scopes-parsing for source and trigger into separate paths
- Emit an error when fields cannot be fully validated due to invalid attribution_scope_limit
- Remove unnecessary lambdas
- Make parsing functions use conventional parameter ordering
=> Clean up attribution-scope parsing

ts/src/header-validator/source.test.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.test.ts, ts/src/header-validator/validate-json.ts
While we wait for the privacy computations to be updated.
=> Disable scope-parsing in header validator by default

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1366.html" title="Last updated on Jul 10, 2024, 2:06 PM UTC (e350fb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1366/1db1ff8...apasel422:e350fb5.html" title="Last updated on Jul 10, 2024, 2:06 PM UTC (e350fb5)">Diff</a>
=> Remove report verification from spec

params/chromium-params.md
Max aggregatable debug reports per source and max destinations per reporting site per day.
=> Add link for two new chromium param values

Makefile, ts/webpack.config.js
After #1370, main corresponds to the command-line header validator, while index corresponds to the web-based validator. Fixing the names here avoids conflicts when building using a mix of webpack and npm.
=> Fix webpack entrypoint naming

ts/src/flexible-event/main.ts, ts/src/header-validator/index.ts, ts/src/header-validator/main.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-eligible.test.ts, ts/src/header-validator/validate-eligible.ts, ts/src/header-validator/validate-info.test.ts, ts/src/header-validator/validate-info.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-os.test.ts, ts/src/header-validator/validate-os.ts, ts/src/header-validator/validator.ts
This makes it easier to guarantee similar operation between the web validator and the command-line one while eliminating redundant logic.
We separate option-construction for the JSON validators from context creation, which is an internal detail of their operation, which enables further encapsulation.
=> Expose common validation/serialization interface for each header

ts/src/header-validator/aggregatable-contributions.test.ts, ts/src/header-validator/aggregatable-contributions.ts, ts/src/header-validator/filters.test.ts, ts/src/header-validator/filters.ts, ts/src/header-validator/reg.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/source.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/trigger.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validator.ts
This will make it easier to split source/trigger parsing into separate files, and removes unnecessary dependencies on parsing.
=> Move parsed source/trigger types to separate files

ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/util.test.ts, ts/src/header-validator/validate-eligible.test.ts, ts/src/header-validator/validate-info.test.ts, ts/src/header-validator/validate-info.ts, ts/src/header-validator/validate-json.test.ts, ts/src/header-validator/validate-os.test.ts
And fix a newly identified bug in the serialization of the Attribution-Reporting-Info header in which the preferred platform was emitted as a string instead of a token.
=> Round-trip all registrations during testing

index.bs
Fixes #1368
When there is no attribution support, set Attribution-Report-Eligible header to empty string to tell the reporting origin that the request is eligible for nothing. We send the empty headers instead of omit the headers as the absence of that header in some contexts still corresponds to the request being trigger-eligible.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1380.html" title="Last updated on Jul 31, 2024, 1:54 AM UTC (3567b17)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1380/99e3b1a...linnan-github:3567b17.html" title="Last updated on Jul 31, 2024, 1:54 AM UTC (3567b17)">Diff</a>
=> Set empty eligible header when there is no attribution support

ts/src/flexible-event/main.ts, ts/src/header-validator/filters-index.ts, ts/src/header-validator/index.ts, ts/src/header-validator/main.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-source.ts, ts/src/header-validator/validate-trigger.ts, ts/src/header-validator/validator.ts
Common functionality is retained in `validate-json.ts`. Source- and trigger-specific functionality is moved into separate files, though unfortunately the diff doesn't indicate that the new files are effectively copied from `validate-json.ts`.
=> Split source/trigger validation into separate files

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-source.ts
To prevent registrations from exceeding the limit when the feature is disabled.
=> Only check max event state limit when scope limit is non-null

attribution_scopes.md, index.bs, ts/src/header-validator/source.test.ts, ts/src/header-validator/source.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/validate-source.ts
Wrap attribution scope fields into a dictionary for clarity.
***
<a href="https://pr-preview.s3.amazonaws.com/feifeiji89/attribution-reporting-api/pull/1391.html" title="Last updated on Aug 12, 2024, 8:28 PM UTC (6611cba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1391/aad5718...feifeiji89:6611cba.html" title="Last updated on Aug 12, 2024, 8:28 PM UTC (6611cba)">Diff</a>
=> Add dictionary for attribution scope fields.

verbose_debugging_reports.md
- Make it clear which fields are always, sometimes, and never present
- Use consistent terminology and descriptions
Fixes #1389
=> Reorganize verbose debugging reports document

index.bs, ts/src/constants.ts, verbose_debugging_reports.md
The current attribution logic in the Attribution Reporting API may not be ideal for use-cases where an ad-tech needs more fine grain control over the attribution granularity (i.e. campaign, product, conversion ID, etc.) before a source is chosen for attribution. Currently available features such as top-level filters are not fully sufficient for this use-case because they happen after a source has been selected (i.e. after attribution). We can optionally support this use-case by allowing callers of the API to specify predefined attribution scopes that will be considered for filtering before attributing a source, in order to more efficiently extract utility out of the API.
This PR covers the attribution and source processing logic.
***
<a …
=> Attribution and source processing logic for Attribution scope.

index.bs
Null report is not associated with any source.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1394.html" title="Last updated on Aug 15, 2024, 3:43 PM UTC (d751942)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1394/1dbcd91...linnan-github:d751942.html" title="Last updated on Aug 15, 2024, 3:43 PM UTC (d751942)">Diff</a>
=> Set null reports's source identifier to null

index.bs, ts/src/constants.ts, ts/src/flexible-event/main.ts, ts/src/flexible-event/privacy.test.ts, ts/src/flexible-event/privacy.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/validate-source.ts, ts/src/vendor-specific-values.ts, verbose_debugging_reports.md
The current attribution logic in the Attribution Reporting API may not be ideal for use-cases where an ad-tech needs more fine grain control over the attribution granularity (i.e. campaign, product, conversion ID, etc.) before a source is chosen for attribution. Currently available features such as top-level filters are not fully sufficient for this use-case because they happen after a source has been selected (i.e. after attribution). We can optionally support this use-case by allowing callers of the API to specify predefined attribution scopes that will be considered for filtering before attributing a source, in order to more efficiently extract utility out of the API.
This PR covers the information gain computation logic:
Given event report configuration `(c, b, w)` definition:
- the …
=> Information gain computation logic for Attribution Scope.

index.bs
This is compatible with currently supported aggregation service versions.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1395.html" title="Last updated on Aug 15, 2024, 6:35 PM UTC (0bd7aa8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1395/cd5c617...linnan-github:0bd7aa8.html" title="Last updated on Aug 15, 2024, 6:35 PM UTC (0bd7aa8)">Diff</a>
=> Omit source_registration_time field while excluding source registration time

index.bs
This algorithm implicitly relied on the implementation defined random delay to shuffle reports, this instead pulls shuffling into it's own step and clarifies the privacy rationale between the non-normative notes.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1387.html" title="Last updated on Aug 7, 2024, 8:19 PM UTC (4385282)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1387/aad5718...4385282.html" title="Last updated on Aug 7, 2024, 8:19 PM UTC (4385282)">Diff</a>
=> Clarify report sending notes and make shuffling explicit

index.bs
This is due to "remote end steps" exported in private aggregation API (https://github.com/patcg-individual-drafts/private-aggregation-api/pull/147).
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1400.html" title="Last updated on Aug 27, 2024, 3:27 PM UTC (bf1b94c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1400/6e2318b...linnan-github:bf1b94c.html" title="Last updated on Aug 27, 2024, 3:27 PM UTC (bf1b94c)">Diff</a>
=> Fix spec build with remote end steps

EVENT.md, index.bs
To improve privacy, source or trigger debug keys will be set in attribution reports only when both are present. This is to avoid privacy leak from one-sided 3P cookie access.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1403.html" title="Last updated on Aug 28, 2024, 2:33 PM UTC (4c64897)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1403/5de498e...linnan-github:4c64897.html" title="Last updated on Aug 28, 2024, 2:33 PM UTC (4c64897)">Diff</a>
=> Only set source or trigger debug keys when both are present

index.bs
Getting rid of sorting with scopes to avoid confusion.
Also added a non-normative note about the rational deleting sources with non-matching scopes.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1406.html" title="Last updated on Aug 31, 2024, 1:14 PM UTC (044f41f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1406/a9a53f5...linnan-github:044f41f.html" title="Last updated on Aug 31, 2024, 1:14 PM UTC (044f41f)">Diff</a>
=> Refactor source matching with attribution scopes

index.bs
The intent of this algorithm is that the pending source is never rejected, but including it in the record list makes it seem like it can be removed; that is only prevented by the "if selectedScopes does not contain record[0]" check.
The pending source's scopes are already included in the selected scopes set, so processing the pending source in the scopeRecords loop is redundant: The insertions will not have effect (the value is already contained), and the containment check vacuously succeeds for the same reason.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1409.html" title="Last updated on Sep 4, 2024, 1:22 PM UTC (2d26cda)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1409/7772278...apasel422:2d26cda …
=> Remove redundant inclusion of pending source in scope records

index.bs
Attribution debug info's fields should be non-negative 64-bit integers, rather than strings, as the rest of the specification treats them as such, delaying the string conversion until the report body is serialized.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1412.html" title="Last updated on Sep 4, 2024, 3:07 PM UTC (efef874)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1412/6821cda...apasel422:efef874.html" title="Last updated on Sep 4, 2024, 3:07 PM UTC (efef874)">Diff</a>
=> Fix type and reference errors in specification

index.bs
Inline [check if existing scopes are compatible with pending scopes](https://wicg.github.io/attribution-reporting-api/#check-if-existing-scopes-are-compatible-with-pending-scopes) algorithm to make the logic clearer.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1414.html" title="Last updated on Sep 4, 2024, 3:28 PM UTC (2539cb6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1414/6821cda...linnan-github:2539cb6.html" title="Last updated on Sep 4, 2024, 3:28 PM UTC (2539cb6)">Diff</a>
=> Simplify attribution scopes processing for new source

index.bs
1. Remove optionality entirely when parameter is always provided by callers.
2. Remove erroneous optionality of non-trailing parameters. (This is prohibited by the Infra spec.)
3. Replace erroneous use of optionality with nullability.
Fixes #1411
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1413.html" title="Last updated on Sep 4, 2024, 3:24 PM UTC (475f02e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1413/65ab440...apasel422:475f02e.html" title="Last updated on Sep 4, 2024, 3:24 PM UTC (475f02e)">Diff</a>
=> Clean up handling of optional parameters in specification

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1416.html" title="Last updated on Sep 4, 2024, 3:55 PM UTC (2c3f2c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1416/311c662...apasel422:2c3f2c8.html" title="Last updated on Sep 4, 2024, 3:55 PM UTC (2c3f2c8)">Diff</a>
=> Fix broken link in specification

index.bs
Rather than re-use the external report UUID for this purpose, since there is a small chance that [it is not actually unique](https://wicg.github.io/uuid/#security).
This also provides a foundation for addressing #1405 using integer sequences, as UUIDs cannot be used to provide an ordering of events.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1421.html" title="Last updated on Sep 10, 2024, 5:46 PM UTC (3e9a941)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1421/d7f363f...apasel422:3e9a941.html" title="Last updated on Sep 10, 2024, 5:46 PM UTC (3e9a941)">Diff</a>
=> Introduce internal report IDs for identity comparisons

index.bs
Null is sometimes an expected value.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1424.html" title="Last updated on Sep 10, 2024, 6:39 PM UTC (452b97a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1424/d7f363f...apasel422:452b97a.html" title="Last updated on Sep 10, 2024, 6:39 PM UTC (452b97a)">Diff</a>
=> Return errors instead of null for clarity and consistency

index.bs
Fixes #1423
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1425.html" title="Last updated on Sep 11, 2024, 1:33 PM UTC (a83fc2c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1425/9a3f6cf...linnan-github:a83fc2c.html" title="Last updated on Sep 11, 2024, 1:33 PM UTC (a83fc2c)">Diff</a>
=> Add default values to registration info

index.bs
Previously we only enforce the limit for non-empty scopes set. It's easier to understand when empty scopes set is also considered.
Also make it clearer in what stage this limit is checked.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1427.html" title="Last updated on Sep 13, 2024, 12:38 AM UTC (d7adbeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1427/21d1eee...linnan-github:d7adbeb.html" title="Last updated on Sep 13, 2024, 12:38 AM UTC (d7adbeb)">Diff</a>
=> Limit 1 unique scopes set per navigation per reporting origin

ts/src/header-validator/index.html, ts/src/header-validator/index.ts, ts/src/header-validator/main.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/to-json.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.test.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-source.ts, ts/src/header-validator/validate-trigger.ts
With scopes now finalized, we can safely enable its behavior by default.
=> Enable Scopes Validation by Default

ts/src/flexible-event/privacy.test.ts, ts/src/flexible-event/privacy.ts
Bit search can yield higher precision than binary search in constant time and
avoid the use of a tolerance.
=> Use bit search for max epsilon

index.bs, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-trigger.ts
Fixes #1434
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1435.html" title="Last updated on Sep 17, 2024, 3:50 PM UTC (23665eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1435/6c726d4...linnan-github:23665eb.html" title="Last updated on Sep 17, 2024, 3:50 PM UTC (23665eb)">Diff</a>
=> Remove aggregation key identifier size limit for trigger registrations

ts/src/flexible-event/privacy.test.ts, ts/src/flexible-event/privacy.ts
- Avoid unnecessary bit operations resulting in bigint construction
- Avoid unnecessary array construction in tests
=> Clean up epsilonToBoundInfoGainAndDp

ts/README.md
Adding visibility to epsilon search could help consumers become more acquainted
with the feature and help elicit feedback about adding such automation to
clients.
(https://wicg.github.io/attribution-reporting-api/#source-registration-json-key-event_level_epsilon)
=> Add epsilon section to README

index.bs
This will make it easier to address #1405, but is beneficial in itself because it indicates the scope of the uniqueness that was previously implicit for strings.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1426.html" title="Last updated on Sep 11, 2024, 2:58 PM UTC (661941e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1426/21d1eee...apasel422:661941e.html" title="Last updated on Sep 11, 2024, 2:58 PM UTC (661941e)">Diff</a>
=> Use increasing integers instead of unique strings for internal IDs

AGGREGATE.md, EVENT.md, index.bs
Fixes #1440
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1441.html" title="Last updated on Oct 15, 2024, 12:55 PM UTC (1ec425a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1441/2877fda...linnan-github:1ec425a.html" title="Last updated on Oct 15, 2024, 12:55 PM UTC (1ec425a)">Diff</a>
=> Remove ar_debug requirement for cookie-based debug reporting

index.bs
Hello,
I believe there's a typo introduced in commit bf3f812cfe568bf45012d642a719407c7cfd1e74. The use of `record` seems ambiguous in this context, and moreover, no `record` objects appear to have an attribute named `internal ID`.
***
<a href="https://pr-preview.s3.amazonaws.com/hiratara/attribution-reporting-api/pull/1462.html" title="Last updated on Nov 12, 2024, 7:55 AM UTC (00fef52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1462/9f7c822...hiratara:00fef52.html" title="Last updated on Nov 12, 2024, 7:55 AM UTC (00fef52)">Diff</a>
=> Correct typo in `get sources to delete for the unexpired destination limit`

ts/src/header-validator/context.ts, ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts
To match the specification, where they do not cause the entire registration to be rejected.
=> Report debug_key/debug_reporting issues as warnings

ts/src/header-validator/source.test.ts, ts/src/header-validator/trigger.test.ts, ts/src/header-validator/validate-json.ts, ts/src/header-validator/validate-source.ts, ts/src/header-validator/validate-trigger.ts, ts/src/header-validator/validate.ts
To match the specification, where they do not cause the entire registration to be rejected.
=> Report aggregatable_debug_reporting issues as warnings

ts/src/header-validator/source.test.ts, ts/src/header-validator/validate.ts
For example, previously https://com would be reported as the warning "URL components other than site (https://null) will be ignored".
=> Use more precise warning when public suffix is used as a destination

index.bs
Per https://wicg.github.io/attribution-reporting-api/#w3c-conventions "these words do not appear in all uppercase letters in this specification."
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1490.html" title="Last updated on Dec 18, 2024, 4:15 PM UTC (48ea07d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1490/51b136f...apasel422:48ea07d.html" title="Last updated on Dec 18, 2024, 4:15 PM UTC (48ea07d)">Diff</a>
=> Lowercase RFC 2119 keywords

AGGREGATE.md, index.bs
The current hard limit on aggregatable reports per source might be too small for
some use-cases. Allowing consumers to manage report counts that already have
privacy constraints applied provides more flexibility. In the case of this
change, when a trigger context ID is supplied, null report rate already manages
the necessary privacy constraints in place of a hard limit on aggregatable
report count.
(See also #1183)
***
<a href="https://pr-preview.s3.amazonaws.com/giladbarkan-github/attribution-reporting-api/pull/1475.html" title="Last updated on Dec 30, 2024, 7:36 PM UTC (2075829)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1475/5b6be31...giladbarkan-github:2075829.html" title="Last updated on Dec 30, 2024, 7:36 PM UTC (2075829)">Diff</a>
=> Remove aggregatable report limit when trigger context ID is non-null

AGGREGATION_SERVICE_TEE.md
With contribution filtering implementation done, the filtering ID is included in the Shared ID generation. Since the data is disjoint between filtering IDs, a report can appear in multiple batches as long as their Shared IDs are not the same across them. This warrants an update to the No Duplicate rule because it is not the reports that shouldn't be duplicated, but the underlying data represented by Shared ID, that shouldn't be.
=> Update No Duplicate Rule to signify that it is Shared Id that can't appear in more than one job, not the reports.

index.bs
This was preventing the spec from being built.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1497.html" title="Last updated on Jan 21, 2025, 7:51 PM UTC (bab8120)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1497/fdb330f...apasel422:bab8120.html" title="Last updated on Jan 21, 2025, 7:51 PM UTC (bab8120)">Diff</a>
=> Fix erroneous end tags in spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/johnivdel/conversion-measurement-api/pull/1496.html" title="Last updated on Jan 21, 2025, 7:15 PM UTC (ede061a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1496/fdb330f...johnivdel:ede061a.html" title="Last updated on Jan 21, 2025, 7:15 PM UTC (ede061a)">Diff</a>
=> Removing johnidel from editors

index.bs
For context, the attribution rate-limit record stores source time (see [here](https://github.com/WICG/attribution-reporting-api/pull/681)).
To be consistent, the check should be performed with the source time as well on trigger registrations.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/1502.html" title="Last updated on Mar 3, 2025, 6:35 PM UTC (ee8c29e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1502/d978cc7...linnan-github:ee8c29e.html" title="Last updated on Mar 3, 2025, 6:35 PM UTC (ee8c29e)">Diff</a>
=> Check with source time for rate-limits on trigger registrations

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1508.html" title="Last updated on Apr 1, 2025, 6:25 PM UTC (9969de2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1508/3e8b1b9...apasel422:9969de2.html" title="Last updated on Apr 1, 2025, 6:25 PM UTC (9969de2)">Diff</a>
=> Remove unnecessary `Note:` prefixes and make error details normative

index.bs
Adds language to allow user-agents to delete reports before delivery based on implementation-defined criteria.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/pull/1505.html" title="Last updated on Apr 1, 2025, 6:50 PM UTC (7841584)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1505/3e8b1b9...7841584.html" title="Last updated on Apr 1, 2025, 6:50 PM UTC (7841584)">Diff</a>
=> Introduce Report Data Lifetime

.github/workflows/build.yml, .gitignore, Makefile
This allows the spec to be built locally even without internet access and provides better log output.
The Makefile setup is derived from [PPA's](https://github.com/w3c/ppa/blob/f23717f290b86eb5390380b2c97ce876b748f2a5/Makefile#L26).
=> Use local bikeshed instead of API service

index.bs
Per https://github.com/whatwg/fetch/pull/1823, this concept is going away. After that change, null-client scenarios will automatically do the right thing, and create no user prompts, which aligns with this spec's desired outcome.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/attribution-reporting-api/pull/1519.html" title="Last updated on May 13, 2025, 5:10 AM UTC (80963b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1519/dace1e2...domenic:80963b6.html" title="Last updated on May 13, 2025, 5:10 AM UTC (80963b6)">Diff</a>
=> Do not set request's window

Makefile, index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1523.html" title="Last updated on May 19, 2025, 2:03 PM UTC (65408db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1523/9a6cb36...apasel422:65408db.html" title="Last updated on May 19, 2025, 2:03 PM UTC (65408db)">Diff</a>
=> Address warnings from building spec

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1522.html" title="Last updated on May 16, 2025, 4:12 PM UTC (bef2573)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1522/9a6cb36...apasel422:bef2573.html" title="Last updated on May 16, 2025, 4:12 PM UTC (bef2573)">Diff</a>
=> Minor typographical enhancements

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1527.html" title="Last updated on May 20, 2025, 3:31 PM UTC (591400f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1527/b14519b...apasel422:591400f.html" title="Last updated on May 20, 2025, 3:31 PM UTC (591400f)">Diff</a>
=> s/an map/a map/

index.bs
With this change, it is possible to click on a variable and see all its uses highlighted within the algorithm scope, and to be warned about missing definitions / unused variables.
https://speced.github.io/bikeshed/#var-and-algorithms
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/attribution-reporting-api/pull/1529.html" title="Last updated on May 22, 2025, 2:02 PM UTC (a731bf5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/1529/30df5c2...apasel422:a731bf5.html" title="Last updated on May 22, 2025, 2:02 PM UTC (a731bf5)">Diff</a>
=> Wrap algorithms in <div algorithm> to generate variable references
